M48
; DRILL file KiCad 10.0.5 date 2026-08-03T02:09:29
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-03T02:09:29-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X103.999Y-84.0
X103.999Y-198.1
X196.099Y-84.0
X196.099Y-198.1
M30
