export interface Project {
  id: string;
  name: string;
  tagline: string;
  description: string;
  category: string;
  techStack: string[];
  impactScore: number;
  stars: number;
  status: "production" | "beta" | "alpha" | "concept";
  githubUrl?: string;
  liveUrl?: string;
  featured: boolean;
  icon: string;
  gradient: string;
}

export const PROJECT_CATEGORIES = [
  "All",
  "AI & Agents",
  "IoT & Smart Home",
  "FinTech",
  "HealthTech",
  "Enterprise",
  "Web & Mobile",
  "Education",
] as const;

export type ProjectCategory = (typeof PROJECT_CATEGORIES)[number];

export const projects: Project[] = [
  {
    id: "nexus-ai-os",
    name: "NEXUS AI OS",
    tagline: "Local-First AI Operating System",
    description:
      "A breathtaking 13+ agent AI operating system running entirely on-device. Personal, financial, health, and home agents orchestrated through Ollama — no cloud dependency. Full-stack spanning FastAPI, React, Electron, React Native, and ESP32 IoT integration, all Docker-composed for single-command deployment.",
    category: "AI & Agents",
    techStack: ["FastAPI", "React", "Electron", "React Native", "Ollama", "ChromaDB", "Docker", "MQTT"],
    impactScore: 98,
    stars: 5,
    status: "beta",
    featured: true,
    icon: "Brain",
    gradient: "from-violet-600 via-purple-600 to-indigo-600",
    githubUrl: "https://github.com/Hemakotibonthada/Jarvis-Ai",
  },
  {
    id: "smarthome-ecosystem",
    name: "SmartHome Ecosystem",
    tagline: "Cross-Platform Home Intelligence",
    description:
      "Production-grade cross-platform home automation built on Flutter, Firebase, and MQTT. Integrates ESP32 firmware, Alexa voice skills, Razorpay payments for e-commerce, and real-time energy monitoring — a complete IoT vertical from silicon to subscription.",
    category: "IoT & Smart Home",
    techStack: ["Flutter", "Firebase", "MQTT", "Riverpod", "ESP32", "Alexa", "Razorpay"],
    impactScore: 95,
    stars: 5,
    status: "production",
    featured: true,
    icon: "Home",
    gradient: "from-cyan-500 via-teal-500 to-emerald-500",
    githubUrl: "https://github.com/Hemakotibonthada/SmartHome",
  },
  {
    id: "cancerguard-ai",
    name: "CancerGuard AI",
    tagline: "AI-Powered Cancer Risk Prediction",
    description:
      "A HIPAA-aligned healthcare AI platform using an ensemble of XGBoost, LightGBM, Random Forest, and Neural Networks for cancer risk prediction. 69 API endpoints serve 3 role-based portals (Patient, Hospital, Admin) with blood donor geo-matching and smartwatch vital integration.",
    category: "HealthTech",
    techStack: ["React", "TypeScript", "FastAPI", "XGBoost", "LightGBM", "Neural Nets", "Material-UI"],
    impactScore: 96,
    stars: 5,
    status: "beta",
    featured: true,
    icon: "HeartPulse",
    gradient: "from-rose-500 via-pink-500 to-fuchsia-500",
    githubUrl: "https://github.com/Hemakotibonthada/CancerDetector",
  },
  {
    id: "vision-ai",
    name: "Vision AI",
    tagline: "Intelligent ESP32-CAM Vision System",
    description:
      "300+ feature embedded vision platform coupling ESP32-CAM hardware with YOLOv8 object detection. Active learning pipeline continuously improves model accuracy. GPU Docker deployment, MQTT real-time streaming, and a React dashboard for live inference monitoring.",
    category: "AI & Agents",
    techStack: ["FastAPI", "React", "ESP32-CAM", "YOLOv8", "Docker", "MQTT", "Redis"],
    impactScore: 93,
    stars: 5,
    status: "beta",
    featured: true,
    icon: "Eye",
    gradient: "from-amber-500 via-orange-500 to-red-500",
    githubUrl: "https://github.com/Hemakotibonthada/Vision-Ai",
  },
  {
    id: "jarvis-ai",
    name: "JARVIS",
    tagline: "Holographic AI Assistant",
    description:
      "An iconic AI assistant with holographic Electron UI, 15 specialized AI skills, and dual-model architecture (GPT-4 + Ollama). Features voice recognition, MQTT smart home control, security tools, web automation via Puppeteer, and an embedded skills framework for infinite extensibility.",
    category: "AI & Agents",
    techStack: ["Node.js", "Electron", "OpenAI GPT-4", "Ollama", "MQTT", "SQLite", "Puppeteer"],
    impactScore: 94,
    stars: 5,
    status: "beta",
    featured: true,
    icon: "Zap",
    gradient: "from-blue-500 via-indigo-500 to-violet-500",
    githubUrl: "https://github.com/Hemakotibonthada/Jarvis-Ai",
  },
  {
    id: "ht-hrms",
    name: "HT Connect",
    tagline: "Enterprise HR + Agile Platform",
    description:
      "Full-featured enterprise HRMS replacing Keka + Jira in a single platform. Sprint boards, burndown charts, leave management, employee onboarding pipelines, performance reviews, and department analytics — built on PostgreSQL/Prisma with a polished Chakra UI.",
    category: "Enterprise",
    techStack: ["Next.js", "Express", "PostgreSQL", "Prisma", "Docker", "Chakra UI"],
    impactScore: 92,
    stars: 5,
    status: "production",
    featured: true,
    icon: "Building2",
    gradient: "from-slate-500 via-zinc-500 to-neutral-500",
    githubUrl: "https://github.com/Hemakotibonthada/HT_HRMS",
  },
  {
    id: "travelmate",
    name: "TravelMate",
    tagline: "AI-Powered Travel Companion",
    description:
      "Comprehensive cross-platform travel application with GPS discovery, real-time multi-language translation, offline map support, and Gemini AI integration. Handles itinerary planning, expense splitting, and social sharing across iOS, Android, and Web.",
    category: "Web & Mobile",
    techStack: ["React Native", "TypeScript", "Firebase", "Google Translate", "Gemini AI", "Expo"],
    impactScore: 90,
    stars: 5,
    status: "production",
    featured: true,
    icon: "Globe",
    gradient: "from-emerald-500 via-green-500 to-lime-500",
    githubUrl: "https://github.com/Hemakotibonthada/Travelmate",
  },
  {
    id: "financial-analyzer",
    name: "Financial Analyzer Pro",
    tagline: "Enterprise Cross-Platform Finance Suite",
    description:
      "Subscription-based financial intelligence platform spanning Web, Mobile, and Desktop. Features AI-powered document analysis, EMI tracking, credit score monitoring, budget optimization, and Razorpay subscription billing with a full admin portal and Firebase Cloud Functions backend.",
    category: "FinTech",
    techStack: ["React", "React Native", "Electron", "Firebase", "Razorpay", "Cloud Functions"],
    impactScore: 91,
    stars: 5,
    status: "production",
    featured: true,
    icon: "TrendingUp",
    gradient: "from-green-500 via-emerald-500 to-teal-500",
    githubUrl: "https://github.com/Hemakotibonthada/financialanalyzer",
  },
  {
    id: "edukanban",
    name: "EduKanban",
    tagline: "AI-Driven Learning Platform",
    description:
      "Production-ready LMS with AI course generation, Kanban-style task management, real-time Socket.IO chat, automated assessments, and learning analytics. MongoDB + Redis backend with Docker deployment and Razorpay payment integration.",
    category: "Education",
    techStack: ["React", "Express", "MongoDB", "Socket.IO", "OpenAI", "Redis", "Docker"],
    impactScore: 89,
    stars: 5,
    status: "production",
    featured: true,
    icon: "GraduationCap",
    gradient: "from-sky-500 via-blue-500 to-indigo-500",
    githubUrl: "https://github.com/Hemakotibonthada/EduKanban",
  },
  {
    id: "stockmarket-agent",
    name: "StockMarket Agent",
    tagline: "Modular Quantitative Trading Engine",
    description:
      "Local-first algorithmic trading agent for Indian equities (NSE). Walk-forward backtesting, paper and live trading modes, broker adapters for Zerodha/Upstox, DuckDB/Parquet data management, and configurable risk management modules.",
    category: "FinTech",
    techStack: ["Python", "DuckDB", "Parquet", "Pydantic", "Streamlit", "Zerodha API"],
    impactScore: 88,
    stars: 4,
    status: "beta",
    featured: true,
    icon: "BarChart3",
    gradient: "from-yellow-500 via-amber-500 to-orange-500",
    githubUrl: "https://github.com/Hemakotibonthada/StockMarket-Agent",
  },
  {
    id: "citadel",
    name: "CITADEL",
    tagline: "Multi-Agent Algorithmic Trading",
    description:
      "Enterprise local-first multi-agent algorithmic trading platform targeting 50K+ LOC. DuckDB and Apache Arrow for zero-copy data sharing, shared memory IPC between agents, Tauri 2.0 + React 19 native desktop UI, and OpenVINO/MLX hardware-accelerated inference.",
    category: "FinTech",
    techStack: ["Python", "Tauri 2.0", "React 19", "DuckDB", "Apache Arrow", "OpenVINO"],
    impactScore: 85,
    stars: 3,
    status: "alpha",
    featured: false,
    icon: "Shield",
    gradient: "from-red-500 via-rose-500 to-pink-500",
    githubUrl: "https://github.com/Hemakotibonthada/CITADEL",
  },
  {
    id: "app-builder",
    name: "App Builder",
    tagline: "Drag-and-Drop Application Platform",
    description:
      "Visual application builder platform with drag-and-drop interface, project management, and code generation. Built on Next.js 15 with Prisma ORM, Redux Toolkit state management, and Framer Motion animations.",
    category: "Enterprise",
    techStack: ["Next.js 15", "React 19", "Prisma", "SQLite", "Redux Toolkit", "Framer Motion"],
    impactScore: 84,
    stars: 4,
    status: "beta",
    featured: false,
    icon: "Layers",
    gradient: "from-indigo-500 via-purple-500 to-pink-500",
    githubUrl: "https://github.com/Hemakotibonthada/App-Builder",
  },
  {
    id: "circuvent-mail",
    name: "Circuvent Mail",
    tagline: "Self-Hosted Email Infrastructure",
    description:
      "Custom self-hosted email system with SMTP support, custom domain integration, admin panel, 25MB attachment handling, and intelligent folder management. Full control over email infrastructure without third-party dependencies.",
    category: "Enterprise",
    techStack: ["React", "Express", "Firebase", "SMTP", "Material-UI"],
    impactScore: 82,
    stars: 4,
    status: "beta",
    featured: false,
    icon: "Mail",
    gradient: "from-blue-400 via-cyan-400 to-teal-400",
    githubUrl: "https://github.com/Hemakotibonthada/Mail",
  },
  {
    id: "health-india",
    name: "Health India",
    tagline: "AI Health Analysis Platform",
    description:
      "Comprehensive health platform with vitals tracking, sleep analytics, disease records, lab test management, and GPT-4 powered risk assessment. Generates personalized health scores and preventive care recommendations.",
    category: "HealthTech",
    techStack: ["Node.js", "React", "MongoDB", "OpenAI GPT-4", "Recharts"],
    impactScore: 83,
    stars: 4,
    status: "beta",
    featured: false,
    icon: "Activity",
    gradient: "from-green-400 via-emerald-400 to-teal-400",
    githubUrl: "https://github.com/Hemakotibonthada/Health_India",
  },
  {
    id: "timecapsule",
    name: "TimeCapsule",
    tagline: "Memory Capture & Preservation",
    description:
      "Adaptive memory timeline application with JWT authentication, Google Photos integration, and native Android capabilities via Ionic Capacitor. Preserves and resurfaces memories with intelligent temporal navigation.",
    category: "Web & Mobile",
    techStack: ["React", "TypeScript", "Express", "Ionic", "Capacitor", "Firebase"],
    impactScore: 81,
    stars: 4,
    status: "beta",
    featured: false,
    icon: "Clock",
    gradient: "from-purple-400 via-violet-400 to-indigo-400",
    githubUrl: "https://github.com/Hemakotibonthada/timeCapsule",
  },
  {
    id: "ats-resume",
    name: "ATS Resume Builder",
    tagline: "AI-Optimized Resume Engineering",
    description:
      "ATS-friendly resume builder with scoring engine (0-100), job description matching, keyword optimization, multiple professional templates, and PDF/DOCX export. Ensures resumes pass automated screening systems.",
    category: "Web & Mobile",
    techStack: ["FastAPI", "React", "Material-UI", "ReportLab", "python-docx"],
    impactScore: 80,
    stars: 4,
    status: "beta",
    featured: false,
    icon: "FileText",
    gradient: "from-teal-400 via-cyan-400 to-sky-400",
    githubUrl: "https://github.com/Hemakotibonthada/ATS-Resume",
  },
  {
    id: "mana-uru",
    name: "Mana Uru",
    tagline: "Indian Village Community Platform",
    description:
      "Community-first social platform for Indian villages featuring social feed, crowdfunding, real-time chat, problem reporting, event management, and multi-language support. Bridging urban-rural digital divide.",
    category: "Web & Mobile",
    techStack: ["React Native", "Expo", "Firebase", "Zustand", "TypeScript"],
    impactScore: 79,
    stars: 4,
    status: "beta",
    featured: false,
    icon: "Users",
    gradient: "from-orange-400 via-amber-400 to-yellow-400",
    githubUrl: "https://github.com/Hemakotibonthada/manauru",
  },
  {
    id: "netshare-pro",
    name: "NetShare Pro",
    tagline: "Enterprise File Sharing",
    description:
      "Cross-platform file sharing tool with standalone desktop builds, high-speed transfer protocol, authentication, comprehensive logging, and complete audit trail. Built as a standalone executable via PyInstaller.",
    category: "Enterprise",
    techStack: ["Python", "Flask", "PyInstaller", "HTML/CSS/JS"],
    impactScore: 78,
    stars: 4,
    status: "production",
    featured: false,
    icon: "Share2",
    gradient: "from-slate-400 via-gray-400 to-zinc-400",
    githubUrl: "https://github.com/Hemakotibonthada/Sharing_Tool",
  },
  {
    id: "bharath-startups",
    name: "Startup Connect India",
    tagline: "Co-Founder Matching Platform",
    description:
      "Startup ecosystem platform enabling co-founder matching, equity agreement management, real-time chat, and investor connections. Monorepo structure with React web and React Native mobile applications.",
    category: "Web & Mobile",
    techStack: ["React", "React Native", "Firebase", "TypeScript", "Vite", "Tailwind"],
    impactScore: 77,
    stars: 4,
    status: "beta",
    featured: false,
    icon: "Rocket",
    gradient: "from-pink-400 via-rose-400 to-red-400",
    githubUrl: "https://github.com/Hemakotibonthada/bharathstartups",
  },
  {
    id: "loan-manager",
    name: "Loan Manager",
    tagline: "Cross-Platform Loan Management",
    description:
      "Complete loan management system handling applications, CIBIL verification, eligibility calculation, and dynamic interest rates. Built with Flutter for seamless cross-platform delivery and Firebase backend.",
    category: "FinTech",
    techStack: ["Flutter", "Firebase", "Cloud Functions", "Firestore"],
    impactScore: 76,
    stars: 4,
    status: "beta",
    featured: false,
    icon: "Landmark",
    gradient: "from-emerald-400 via-green-400 to-lime-400",
    githubUrl: "https://github.com/Hemakotibonthada/Loan",
  },
  {
    id: "guide-me",
    name: "Guide Me",
    tagline: "AI Travel Planning & Discovery",
    description:
      "AI-powered travel planning platform with Google Maps integration, itinerary optimization, expense tracking, and cross-platform delivery via Ionic Capacitor for iOS, Android, and PWA.",
    category: "Web & Mobile",
    techStack: ["Ionic 7", "Angular 17", "Firebase", "Google Maps", "OpenAI", "Capacitor"],
    impactScore: 75,
    stars: 4,
    status: "beta",
    featured: false,
    icon: "Map",
    gradient: "from-sky-400 via-blue-400 to-indigo-400",
    githubUrl: "https://github.com/Hemakotibonthada/Guide_Me",
  },
  {
    id: "neural-sentinel",
    name: "Neural Sentinel",
    tagline: "NPU-Accelerated Stock Trading",
    description:
      "Autonomous stock trading agent optimized for Intel NPU hardware. DeepSeek-R1 inference via OpenVINO, real-time market data piping, risk guard rails, and native PySide6/Qt desktop GUI with PDF report generation.",
    category: "FinTech",
    techStack: ["Python", "OpenVINO", "PySide6", "Qt", "yfinance", "ReportLab"],
    impactScore: 74,
    stars: 3,
    status: "alpha",
    featured: false,
    icon: "Cpu",
    gradient: "from-violet-400 via-purple-400 to-fuchsia-400",
    githubUrl: "https://github.com/Hemakotibonthada/stockmarket",
  },
  {
    id: "smarthome-ai",
    name: "SmartHome AI",
    tagline: "AI-Enhanced Home Automation",
    description: "Advanced AI-powered home automation system with intelligent scene management, predictive energy optimization, and natural language control. Extends the SmartHome ecosystem with machine learning capabilities.",
    category: "IoT & Smart Home",
    techStack: ["Python", "FastAPI", "Ollama", "MQTT", "ESP32", "Docker"],
    impactScore: 86,
    stars: 4,
    status: "beta",
    featured: false,
    icon: "Home",
    gradient: "from-cyan-400 via-teal-400 to-emerald-400",
    githubUrl: "https://github.com/Hemakotibonthada/SmartHome-Ai",
  },
  {
    id: "homeautomation-pro",
    name: "HomeAutomation Pro",
    tagline: "Professional IoT Control Suite",
    description: "Professional-grade IoT home automation with advanced scheduling, multi-zone control, energy analytics, and integration with popular smart home platforms.",
    category: "IoT & Smart Home",
    techStack: ["Flutter", "Firebase", "MQTT", "ESP32", "Node.js"],
    impactScore: 84,
    stars: 4,
    status: "production",
    featured: false,
    icon: "Home",
    gradient: "from-teal-400 via-cyan-400 to-sky-400",
    githubUrl: "https://github.com/Hemakotibonthada/HomeAutomation_Pro",
  },
  {
    id: "dharma-yatra",
    name: "DharmaYatra",
    tagline: "Spiritual Travel Platform",
    description: "Comprehensive spiritual travel platform for temple pilgrimages across India. Features route planning, temple information, accommodation booking, and community reviews.",
    category: "Web & Mobile",
    techStack: ["React Native", "Firebase", "Google Maps", "TypeScript"],
    impactScore: 73,
    stars: 3,
    status: "beta",
    featured: false,
    icon: "Map",
    gradient: "from-amber-400 via-orange-400 to-red-400",
    githubUrl: "https://github.com/Hemakotibonthada/DharmaYatra",
  },
  {
    id: "microhabit",
    name: "MicroHabit",
    tagline: "Micro-Habit Building Engine",
    description: "Behavioral science-backed habit formation app using micro-habit methodology. Features streak tracking, habit stacking, analytics, and AI-powered recommendations.",
    category: "HealthTech",
    techStack: ["React", "TypeScript", "Firebase", "Tailwind CSS"],
    impactScore: 72,
    stars: 3,
    status: "beta",
    featured: false,
    icon: "Activity",
    gradient: "from-lime-400 via-green-400 to-emerald-400",
    githubUrl: "https://github.com/Hemakotibonthada/MicroHabit",
  },
  {
    id: "memorylane",
    name: "MemoryLane",
    tagline: "AI-Powered Memory Vault",
    description: "Intelligent memory preservation platform using AI for auto-tagging, face recognition, and smart album creation. Supports photos, videos, and voice memos.",
    category: "Web & Mobile",
    techStack: ["React", "Node.js", "MongoDB", "TensorFlow.js", "Firebase"],
    impactScore: 71,
    stars: 3,
    status: "beta",
    featured: false,
    icon: "Clock",
    gradient: "from-rose-400 via-pink-400 to-violet-400",
    githubUrl: "https://github.com/Hemakotibonthada/MEMORYLANE",
  },
  {
    id: "pricemind",
    name: "PriceMind",
    tagline: "AI Price Comparison Engine",
    description: "Intelligent price comparison and tracking platform using web scraping and ML. Features price drop alerts, historical price charts, and deal scoring across e-commerce platforms.",
    category: "AI & Agents",
    techStack: ["Python", "FastAPI", "React", "Selenium", "PostgreSQL"],
    impactScore: 70,
    stars: 3,
    status: "alpha",
    featured: false,
    icon: "TrendingUp",
    gradient: "from-yellow-400 via-amber-400 to-orange-400",
    githubUrl: "https://github.com/Hemakotibonthada/PriceMind",
  },
  {
    id: "skillbank",
    name: "SkillBank",
    tagline: "Skill Marketplace Platform",
    description: "Peer-to-peer skill exchange and learning marketplace. Users can teach skills they know and learn skills from others — a barter economy for expertise.",
    category: "Education",
    techStack: ["React", "Express", "MongoDB", "Socket.IO", "Stripe"],
    impactScore: 69,
    stars: 3,
    status: "beta",
    featured: false,
    icon: "GraduationCap",
    gradient: "from-indigo-400 via-blue-400 to-cyan-400",
    githubUrl: "https://github.com/Hemakotibonthada/skillbank",
  },
  {
    id: "jobportal",
    name: "JobPortal",
    tagline: "AI-Powered Job Matching",
    description: "Full-featured job portal with AI resume matching, employer dashboards, applicant tracking, and automated screening. Supports multiple job categories and experience levels.",
    category: "Enterprise",
    techStack: ["React", "Node.js", "PostgreSQL", "Redis", "Docker"],
    impactScore: 68,
    stars: 3,
    status: "beta",
    featured: false,
    icon: "Users",
    gradient: "from-sky-400 via-blue-400 to-violet-400",
    githubUrl: "https://github.com/Hemakotibonthada/JobPortal",
  },
];

export const getProjectsByCategory = (category: ProjectCategory): Project[] => {
  if (category === "All") return projects;
  return projects.filter((p) => p.category === category);
};

export const getFeaturedProjects = (): Project[] => {
  return projects.filter((p) => p.featured).sort((a, b) => b.impactScore - a.impactScore);
};

export const stats = {
  totalProjects: 53,
  productionApps: 8,
  techStacks: 15,
  linesOfCode: "200K+",
  aiModels: 12,
  iotDevices: 9,
};
