// ──────────────────────────────────────────────────────────────
// Report Template — Generic PDF report generation for
// compliance reports, financial summaries, and fleet reports.
// ──────────────────────────────────────────────────────────────

import { PDFRenderer, PDFTableColumn } from "../pdf.renderer";

export interface ReportInput {
  title: string;
  subtitle?: string;
  generatedBy: string;
  period?: { from: string; to: string };
  summary: { label: string; value: string }[];
  sections: {
    title: string;
    type: "table" | "key-value" | "text";
    data: any;
    columns?: PDFTableColumn[];
  }[];
  footer?: string;
}

export async function generateReportPDF(input: ReportInput): Promise<{ buffer: Buffer; checksum: string }> {
  const renderer = new PDFRenderer({
    title: input.title,
    subtitle: input.subtitle || (input.period ? `${input.period.from} to ${input.period.to}` : undefined),
    companyName: "Circuvent Technologies Pvt. Ltd.",
    companyAddress: "HSR Layout, Bengaluru, Karnataka 560102",
    pageSize: "A4",
    orientation: input.sections.some((s) => s.columns && s.columns.length > 5) ? "landscape" : "portrait",
  });

  renderer.renderHeader();

  // Summary section
  if (input.summary.length > 0) {
    renderer.renderKeyValueSection("Report Summary", input.summary.map((s) => [s.label, s.value] as [string, string]), 3);
    renderer.moveDown(0.5);
  }

  // Generated metadata
  renderer.renderKeyValueSection("Report Metadata", [
    ["Generated By", input.generatedBy],
    ["Generated At", new Date().toLocaleString("en-IN")],
    ...(input.period ? [["Period", `${input.period.from} to ${input.period.to}`] as [string, string]] : []),
    ["Report ID", `RPT-${Date.now().toString(36).toUpperCase()}`],
  ], 2);

  renderer.moveDown(1);

  // Render each section
  for (const section of input.sections) {
    if (section.type === "table" && section.columns) {
      renderer.moveDown(0.5);
      renderer.renderKeyValueSection(section.title, [], 1);
      renderer.renderTable(section.columns, section.data);
    } else if (section.type === "key-value") {
      renderer.renderKeyValueSection(section.title, section.data as [string, string][], 2);
    } else if (section.type === "text") {
      renderer.renderNote(section.data as string);
    }
    renderer.moveDown(0.5);
  }

  renderer.renderNote(input.footer || "This report is system-generated and intended for internal use only. Confidential.");
  renderer.renderFooter();

  return renderer.toBuffer();
}

// ── Pre-built report factories ──

export function buildPayrollSummaryReport(data: {
  month: string;
  year: number;
  totalEmployees: number;
  totalGross: number;
  totalDeductions: number;
  totalNet: number;
  byDepartment: { department: string; headcount: number; grossPay: number; netPay: number }[];
  generatedBy: string;
}): ReportInput {
  return {
    title: "Monthly Payroll Summary Report",
    subtitle: `${data.month} ${data.year}`,
    generatedBy: data.generatedBy,
    summary: [
      { label: "Total Employees", value: String(data.totalEmployees) },
      { label: "Total Gross", value: `₹${data.totalGross.toLocaleString("en-IN")}` },
      { label: "Total Deductions", value: `₹${data.totalDeductions.toLocaleString("en-IN")}` },
      { label: "Total Net Pay", value: `₹${data.totalNet.toLocaleString("en-IN")}` },
    ],
    sections: [
      {
        title: "Department-wise Breakdown",
        type: "table",
        columns: [
          { header: "Department", key: "department", width: 150 },
          { header: "Headcount", key: "headcount", width: 80, align: "center" },
          { header: "Gross Pay", key: "grossPay", width: 120, align: "right", format: (v: any) => `₹${Number(v).toLocaleString("en-IN")}` },
          { header: "Net Pay", key: "netPay", width: 120, align: "right", format: (v: any) => `₹${Number(v).toLocaleString("en-IN")}` },
        ],
        data: data.byDepartment,
      },
    ],
  };
}

export function buildFleetStatusReport(data: {
  totalDevices: number;
  online: number;
  offline: number;
  maintenance: number;
  criticalAlerts: number;
  devices: { code: string; name: string; status: string; firmware: string; lastSeen: string; alerts: number }[];
  generatedBy: string;
}): ReportInput {
  return {
    title: "IoT Fleet Status Report",
    generatedBy: data.generatedBy,
    summary: [
      { label: "Total Devices", value: String(data.totalDevices) },
      { label: "Online", value: String(data.online) },
      { label: "Offline", value: String(data.offline) },
      { label: "Maintenance", value: String(data.maintenance) },
      { label: "Critical Alerts", value: String(data.criticalAlerts) },
    ],
    sections: [
      {
        title: "Device Inventory",
        type: "table",
        columns: [
          { header: "Code", key: "code", width: 80 },
          { header: "Name", key: "name", width: 150 },
          { header: "Status", key: "status", width: 80 },
          { header: "Firmware", key: "firmware", width: 70 },
          { header: "Last Seen", key: "lastSeen", width: 100 },
          { header: "Alerts", key: "alerts", width: 50, align: "center" },
        ],
        data: data.devices,
      },
    ],
  };
}

export function buildRnDTaxReport(data: {
  financialYear: string;
  totalAmount: number;
  byCategory: { category: string; amount: number; count: number }[];
  records: { description: string; amount: number; category: string; source: string; date: string }[];
  generatedBy: string;
}): ReportInput {
  return {
    title: "R&D Tax Benefit Report",
    subtitle: `Financial Year ${data.financialYear}`,
    generatedBy: data.generatedBy,
    summary: [
      { label: "Financial Year", value: data.financialYear },
      { label: "Total R&D Expenditure", value: `₹${data.totalAmount.toLocaleString("en-IN")}` },
      { label: "Total Records", value: String(data.records.length) },
      { label: "Categories", value: String(data.byCategory.length) },
    ],
    sections: [
      {
        title: "Category-wise Summary",
        type: "table",
        columns: [
          { header: "Category", key: "category", width: 200 },
          { header: "Records", key: "count", width: 80, align: "center" },
          { header: "Amount", key: "amount", width: 120, align: "right", format: (v: any) => `₹${Number(v).toLocaleString("en-IN")}` },
        ],
        data: data.byCategory,
      },
      {
        title: "Detailed Records",
        type: "table",
        columns: [
          { header: "Description", key: "description", width: 200 },
          { header: "Category", key: "category", width: 100 },
          { header: "Source", key: "source", width: 80 },
          { header: "Date", key: "date", width: 80 },
          { header: "Amount", key: "amount", width: 100, align: "right", format: (v: any) => `₹${Number(v).toLocaleString("en-IN")}` },
        ],
        data: data.records,
      },
    ],
    footer: "This report is prepared for internal use in computing R&D tax benefits under Section 35(2AB) of the Income Tax Act, 1961.",
  };
}
