M48
; DRILL file KiCad 10.0.5 date 2026-08-03T03:26:35
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-03T03:26:35-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X139.315Y-119.365
X145.095Y-119.365
T2
X103.999Y-84.0
X173.799Y-136.4
M30
