import React, { useCallback, useEffect, useMemo, useState } from "react";
import { Pressable, Text, View } from "react-native";
import Svg, { Circle, Line, Text as SvgText } from "react-native-svg";
import { api } from "../../../api";
import type { Device } from "../../../api";
import { fleetHealth, formatRelative, groupBy } from "../../../enterprise";
import { Screen, Card, ErrorState, EmptyState, useTheme } from "../../../ui";
import { BottomSheet, Callout, CodeBlock, CopyField, HealthStrip, MetricRow, Pill, ScreenHeader, LoadingState } from "../../../enterprise-ui";
import { deviceRoom, Page, pretty, statusOfDevice } from "./parts";
import { logDiagnostic } from "./log";

function statusColor(c: ReturnType<typeof useTheme>["c"], d: Device): string { const s = statusOfDevice(d); return s === "online" ? c.green : s === "stale" ? c.amber : c.red; }

export default function ConnectivityMap({ onBack }: { onBack: () => void }) {
  const { c } = useTheme(); const [devices, setDevices] = useState<Device[]>([]); const [rooms, setRooms] = useState<string[]>([]); const [selected, setSelected] = useState<Device>(); const [loading, setLoading] = useState(true); const [error, setError] = useState<string>();
  const load = useCallback(async () => { setLoading(true); setError(undefined); try { const [dev, roomRes] = await Promise.all([api.devices(), api.rooms()]); if (!dev.ok) throw new Error(String((dev.data as any)?.error ?? "Devices failed")); setDevices(dev.data.devices); const roomNames = roomRes.ok ? roomRes.data.rooms.map((r) => r.name) : []; setRooms([...new Set([...roomNames, ...dev.data.devices.map(deviceRoom)])]); await logDiagnostic({ severity: "info", kind: "refresh", title: "Connectivity map refreshed", detail: `${dev.data.devices.length} devices` }); } catch (e) { setError(e instanceof Error ? e.message : "Load failed"); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const fh = useMemo(() => fleetHealth(devices), [devices]); const byRoom = useMemo(() => groupBy(devices, (d) => deviceRoom(d)), [devices]); const byType = useMemo(() => groupBy(devices, (d) => d.type || "unknown"), [devices]); const stale = devices.filter((d) => statusOfDevice(d) === "stale");
  const nodes = useMemo(() => { const out: { d: Device; x: number; y: number; room: string }[] = []; const W = 320, H = 280, cx = W / 2, cy = H / 2; const roomList = Object.keys(byRoom); roomList.forEach((room, ri) => { const angle = (ri / Math.max(1, roomList.length)) * Math.PI * 2 - Math.PI / 2; const rx = cx + Math.cos(angle) * 105; const ry = cy + Math.sin(angle) * 88; byRoom[room].forEach((d, di) => { const local = (di / Math.max(1, byRoom[room].length)) * Math.PI * 2; out.push({ d, room, x: rx + Math.cos(local) * 22, y: ry + Math.sin(local) * 22 }); }); }); return out; }, [byRoom]);
  return <Screen><ScreenHeader title="Connectivity map" subtitle="Real rooms, types, and online state" onBack={onBack} actions={[{ icon: "refresh", label: "Refresh", onPress: load }]} />
    <Page>{loading ? <LoadingState text="Mapping real devices…" /> : error ? <ErrorState text={error} onRetry={load} /> : devices.length ? <>
      <HealthStrip items={[{ label: "Devices", ok: fh.total > 0, detail: String(fh.total) }, { label: "Online", ok: fh.online > 0, detail: `${Math.round(fh.onlinePct)}%` }, { label: "Stale online", ok: fh.stale === 0, detail: String(fh.stale) }]} />
      {stale.length ? <Callout kind="warning" icon="warning" title="Stale online devices" text={stale.map((d) => `${d.name} last seen ${formatRelative(d.last_seen)}`).join("; ")} /> : null}
      <Card padded style={{ marginBottom: 12 }}><Text style={{ color: c.text, fontWeight: "900", marginBottom: 8 }}>Topology</Text><Svg width="100%" height={300} viewBox="0 0 320 300"><Circle cx={160} cy={145} r={36} fill={c.accent} opacity={0.92} /><SvgText x={160} y={140} fill={c.onAccent} fontSize="11" fontWeight="700" textAnchor="middle">control</SvgText><SvgText x={160} y={154} fill={c.onAccent} fontSize="11" fontWeight="700" textAnchor="middle">plane</SvgText>{nodes.map((n) => <Line key={`l-${n.d.id}`} x1={160} y1={145} x2={n.x} y2={n.y} stroke={c.borderHi} strokeWidth={1.5} />)}{rooms.map((r, i) => { const angle = (i / Math.max(1, rooms.length)) * Math.PI * 2 - Math.PI / 2; return <SvgText key={r} x={160 + Math.cos(angle) * 122} y={145 + Math.sin(angle) * 102} fill={c.faint} fontSize="10" textAnchor="middle">{r.slice(0, 12)}</SvgText>; })}{nodes.map((n) => <React.Fragment key={n.d.id}><Circle cx={n.x} cy={n.y} r={12} fill={statusColor(c, n.d)} /><Circle cx={n.x} cy={n.y} r={15} fill="transparent" onPress={() => setSelected(n.d)} /><SvgText x={n.x} y={n.y + 27} fill={c.textDim} fontSize="8" textAnchor="middle">{n.d.name.slice(0, 9)}</SvgText></React.Fragment>)}</Svg><View style={{ flexDirection: "row", flexWrap: "wrap", gap: 8 }}><Pill label="online" color={c.green} /><Pill label="stale" color={c.amber} /><Pill label="offline" color={c.red} /></View></Card>
      <Card padded style={{ marginBottom: 12 }}><Text style={{ color: c.text, fontWeight: "900", marginBottom: 8 }}>Rooms and devices</Text>{Object.entries(byRoom).map(([room, list], i) => <MetricRow key={room} label={room} value={`${list.length} devices · ${list.filter((d) => d.online).length} online`} icon="rooms" last={i === Object.keys(byRoom).length - 1} />)}</Card>
      <Card padded><Text style={{ color: c.text, fontWeight: "900", marginBottom: 8 }}>Types</Text>{Object.entries(byType).map(([type, list], i) => <MetricRow key={type} label={type} value={String(list.length)} icon="sensors" last={i === Object.keys(byType).length - 1} />)}</Card>
      <BottomSheet visible={!!selected} onClose={() => setSelected(undefined)} title={selected?.name || "Device"}>{selected ? <><CopyField label="Device ID" value={selected.id} /><MetricRow label="Type" value={selected.type} icon="device" /><MetricRow label="Room" value={deviceRoom(selected)} icon="rooms" /><MetricRow label="Firmware" value={selected.fw_version || "—"} icon="firmware" /><MetricRow label="Last seen" value={formatRelative(selected.last_seen)} icon="clock" /><MetricRow label="State" value={statusOfDevice(selected)} icon="online" last /><CodeBlock text={pretty(selected.state)} label="Current state" maxHeight={320} /></> : null}</BottomSheet>
    </> : <EmptyState icon="topology" title="No devices" subtitle="The topology is drawn only from real device rows." actionLabel="Refresh" onAction={load} />}</Page></Screen>;
}
