import React, { useCallback, useEffect, useMemo, useState } from "react";
import { Text, View } from "react-native";
import { api } from "../../../api";
import { fleetHealth } from "../../../enterprise";
import { Screen, Card, EmptyState, useTheme } from "../../../ui";
import { ActionButton, BottomSheet, CodeBlock, ConfirmDialog, FilterBar, MetricRow, ScreenHeader, SearchField, SeverityBadge } from "../../../enterprise-ui";
import type { Severity } from "../../../enterprise";
import { fmtMs, latencyStats, Page } from "./parts";
import { clearDiagnosticLogs, getLogs, makeSupportBundle, subscribeLogs, type DiagnosticLogEntry } from "./log";
import { logDiagnostic } from "./log";
import { useHealthProbe } from "./useProbe";

type Filter = "all" | Severity;
const filters: { value: Filter; label: string }[] = [{ value: "all", label: "All" }, { value: "critical", label: "Critical" }, { value: "warning", label: "Warning" }, { value: "info", label: "Info" }, { value: "success", label: "Success" }];

export default function DiagnosticLog({ onBack }: { onBack: () => void }) {
  const { c } = useTheme(); const [entries, setEntries] = useState<DiagnosticLogEntry[]>([]); const [filter, setFilter] = useState<Filter>("all"); const [q, setQ] = useState(""); const [selected, setSelected] = useState<DiagnosticLogEntry>(); const [confirm, setConfirm] = useState(false); const [bundle, setBundle] = useState<string>(); const probe = useHealthProbe(15000);
  useEffect(() => subscribeLogs(setEntries), []);
  const counts = useMemo(() => ({ all: entries.length, critical: entries.filter((e) => e.severity === "critical").length, warning: entries.filter((e) => e.severity === "warning").length, info: entries.filter((e) => e.severity === "info").length, success: entries.filter((e) => e.severity === "success").length }), [entries]);
  const filtered = entries.filter((e) => (filter === "all" || e.severity === filter) && `${e.title} ${e.detail ?? ""} ${e.kind}`.toLowerCase().includes(q.toLowerCase()));
  const clear = useCallback(async () => { await clearDiagnosticLogs(); setConfirm(false); }, []);
  const copyBundle = useCallback(async () => { const dev = await api.devices(); const devices = dev.ok ? dev.data.devices : []; const fh = fleetHealth(devices); const errors = (await getLogs()).filter((e) => e.severity === "critical" || e.severity === "warning"); const ok = probe.samples.filter((s) => s.ok).map((s) => s.ms); const st = latencyStats(ok); const text = makeSupportBundle({ deviceCount: fh.total, online: fh.online, stale: fh.stale, lastProbe: ok.length ? { samples: ok.length, minMs: st.min, avgMs: st.avg, p95Ms: st.p95, maxMs: st.max, note: "HTTP round-trip to control plane from this device via api.health()." } : undefined, errors }); setBundle(text); await logDiagnostic({ severity: "info", kind: "support", title: "Support bundle assembled", detail: "Token and secrets excluded" }); }, [probe.samples]);
  return <Screen><ScreenHeader title="Diagnostic log" subtitle="Local app-side observability" onBack={onBack} actions={[{ icon: "debug", label: "Bundle", onPress: copyBundle }, { icon: "trash", label: "Clear", onPress: () => setConfirm(true), tint: c.red }]} />
    <Page><Text style={{ color: c.faint, marginBottom: 12 }}>This local ring buffer records real client-side diagnostic events generated by these screens: probes, refreshes, failed API calls, and command dispatches.</Text>
      <FilterBar options={filters} value={filter} onChange={setFilter} counts={counts} /><SearchField value={q} onChange={setQ} placeholder="Search local log" />
      <Card padded style={{ marginBottom: 12 }}><MetricRow label="Last probe average" value={fmtMs(probe.stats.avg)} icon="latency" /><MetricRow label="Probe samples" value={String(probe.samples.length)} icon="packet" /><MetricRow label="Recent warnings/errors" value={String(counts.warning + counts.critical)} icon="warning" last /></Card>
      {filtered.length ? <Card padded>{filtered.map((e, i) => <MetricRow key={e.id} label={e.title} value={<View style={{ alignItems: "flex-end", maxWidth: 190 }}><SeverityBadge severity={e.severity} /><Text onPress={() => setSelected(e)} accessibilityRole="button" accessibilityLabel={`Open ${e.title}`} style={{ color: c.accentHi, fontSize: 12, fontWeight: "800", marginTop: 4 }} numberOfLines={1}>{e.kind} · {new Date(e.ts).toLocaleTimeString()}</Text></View>} icon={e.severity === "warning" || e.severity === "critical" ? "warning" : "info"} last={i === filtered.length - 1} />)}</Card> : <EmptyState icon="logs" title="No log entries" subtitle="Run probes or refresh diagnostics to create real entries." />}
      <BottomSheet visible={!!selected} onClose={() => setSelected(undefined)} title="Log entry"><CodeBlock text={JSON.stringify(selected, null, 2)} label="Entry JSON" maxHeight={520} /></BottomSheet>
      <BottomSheet visible={!!bundle} onClose={() => setBundle(undefined)} title="Support bundle"><CodeBlock text={bundle || ""} label="No secrets included" maxHeight={560} /></BottomSheet>
      <ConfirmDialog visible={confirm} title="Clear diagnostic log?" message="This removes the local diagnostics ring buffer from this device." destructive confirmLabel="Clear all" onConfirm={clear} onCancel={() => setConfirm(false)} />
    </Page></Screen>;
}
