import { readFileSync } from "fs";
import { join } from "path";

const raw = JSON.parse(readFileSync(join(process.cwd(), "mobile/app.json"), "utf8")).expo as {
  version: string;
  android: { versionCode: number; package: string };
  ios: { buildNumber: string; bundleIdentifier: string; infoPlist: Record<string, string> };
  plugins: unknown[];
};
const expo = raw;

/**
 * Google Play's target API floor.
 *
 * Play refuses updates to an app whose target API is more than a year behind
 * the current Android release. From 31 August 2026 that means API 36; the app
 * was on 35 and the console had already raised the policy notice. Missing it
 * does not degrade anything — it stops updates being published at all, so a
 * fix ready to ship would have nowhere to go.
 *
 * This is a floor, not a pin: raising it further is always fine, and the
 * number only ever needs revisiting when Play moves the requirement again.
 */
const PLAY_MIN_TARGET_SDK = 36;

function buildProperties(): { compileSdkVersion?: number; targetSdkVersion?: number; buildToolsVersion?: string } {
  for (const plugin of expo.plugins ?? []) {
    if (Array.isArray(plugin) && plugin[0] === "expo-build-properties") {
      return ((plugin[1] as { android?: Record<string, never> })?.android ?? {}) as never;
    }
  }
  return {};
}

describe("Android target API meets Google Play's requirement", () => {
  const android = buildProperties();

  it(`targets API ${PLAY_MIN_TARGET_SDK} or higher`, () => {
    expect(android.targetSdkVersion).toBeGreaterThanOrEqual(PLAY_MIN_TARGET_SDK);
  });

  it("compiles against at least what it targets", () => {
    // Targeting an API the app was not compiled against is not a configuration
    // anyone should ship: the new platform behaviours switch on without the
    // corresponding APIs being available to compile against.
    expect(android.compileSdkVersion).toBeGreaterThanOrEqual(android.targetSdkVersion as number);
  });

  it("uses build tools matching the compile SDK", () => {
    expect(android.buildToolsVersion).toBe(`${android.compileSdkVersion}.0.0`);
  });

  /*
   * android/ is generated by prebuild and gitignored, so app.json is the only
   * copy of these values under version control. If that ever stops being true,
   * editing app.json alone would silently change nothing.
   */
  it("is configured in app.json, which is the version-controlled source", () => {
    expect(android.targetSdkVersion).toBeDefined();
    expect(android.compileSdkVersion).toBeDefined();
  });
});

/*
 * The two platforms ship the same app from the same source, and nothing was
 * keeping their build numbers together. Android had reached 14 while iOS was
 * still on 8 — six releases of drift, invisible because each store only ever
 * sees its own number, and nothing in the build bumps the iOS one.
 *
 * The consequence is not cosmetic: "build 12" has to mean one thing when
 * somebody reports a bug, and an iOS build carrying a number six behind the
 * code in it is a debugging trap.
 */
describe("the two platforms ship the same build", () => {
  it("keeps the iOS build number in step with the Android version code", () => {
    /*
     * This has now caught the same drift twice in a day, both times because
     * android.versionCode was bumped on its own. The fix is always to set
     * ios.buildNumber to the same number in mobile/app.json — the failure
     * otherwise reads as "18 is not 19" and leaves the next person to work out
     * which of the two is wrong.
     */
    expect(expo.ios.buildNumber).toBe(String(expo.android.versionCode));
  });

  it("ships from one version number", () => {
    expect(expo.version).toMatch(/^\d+\.\d+\.\d+$/);
  });

  it("is the same app on both stores", () => {
    expect(expo.android.package).toBe("com.circuvent.app");
    expect(expo.ios.bundleIdentifier).toBe("com.circuvent.app");
  });
});

/*
 * A missing usage description does not fail on iOS, it terminates the process.
 * For the app lock that means closing on launch, on every Face ID iPhone, while
 * Android and Touch ID Macs behave perfectly — so it is worth asserting here as
 * well as in the build guard, because this suite runs on every change and the
 * build guard only runs before a build.
 */
describe("iOS usage descriptions for everything the app can trigger", () => {
  it.each([
    ["NSFaceIDUsageDescription", "the app lock"],
    ["NSCameraUsageDescription", "scanning a device QR code"],
    ["NSLocationWhenInUseUsageDescription", "presence automations"],
    ["NSLocalNetworkUsageDescription", "finding devices on the network"],
  ])("has %s, for %s", (key) => {
    const value = expo.ios.infoPlist[key];
    expect(typeof value).toBe("string");
    // Apple rejects boilerplate, and a vague string is also useless to the
    // person being asked; a real sentence is the minimum bar.
    expect((value ?? "").length).toBeGreaterThan(25);
  });
});
