"""
Drawn figures for the architecture deck, and a raster cache for real artwork.

WHY DRAW RATHER THAN DESCRIBE

The architecture deck was tables and prose, and both are the wrong shape for the
questions it answers. "What talks to what" is a picture. "Which certificate is
ours" is a picture. "Why does the flat stop working when the router dies" is
very much a picture, and three bullet points about Wi-Fi channels do not land
the way two rows of boxes on different channels do.

Everything here is vector, built from the same shape helpers as the rest of the
company's decks, so it stays crisp at any zoom and matches the palette in
`src/app/globals.css` rather than being screenshots that go stale.

WHY THE RASTERISER EXISTS

python-pptx will not embed an SVG, and every piece of product artwork in this
repository is one — generated by `scripts/gen-product-art.js`, which is the
single owner of what a device looks like. Rather than keep a second set of
hand-exported PNGs that would drift from it, the SVGs are rasterised at build
time into `Docs/kt/_assets/` and embedded from there.

That directory is a build artifact. It is derived from public/img and can be
deleted at any time; the next build puts it back.
"""

from __future__ import annotations

from pathlib import Path

from pptx.util import Inches, Pt
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import PP_ALIGN

from business_docs.brand import (
    CYAN, CYAN_BRIGHT, VIOLET, INK, INK_DEEP, SLATE, MUTED, PAPER, PAPER_ALT,
)
from business_docs.decks import W, H, _text, _rect, _rgb

ROOT = Path(__file__).resolve().parent.parent.parent
ASSETS = ROOT / "Docs" / "kt" / "_assets"


# --------------------------------------------------------------------------
# Raster cache
# --------------------------------------------------------------------------

def svg_png(name: str, scale: int = 2) -> Path | None:
    """
    Rasterise `public/img/<name>.svg` once and return the PNG.

    Returns None rather than raising when the source is missing or the renderer
    cannot read it: a deck that fails to build because one illustration moved is
    worse than a deck with one illustration missing, and the verifier checks
    that the pictures arrived rather than trusting this to have worked.
    """
    src = ROOT / "public" / "img" / f"{name}.svg"
    if not src.is_file():
        return None
    ASSETS.mkdir(parents=True, exist_ok=True)
    out = ASSETS / f"{name}.png"
    if out.is_file() and out.stat().st_mtime >= src.stat().st_mtime:
        return out
    try:
        import fitz  # PyMuPDF, already used by the document verifiers
        with fitz.open(str(src)) as doc:
            pix = doc[0].get_pixmap(matrix=fitz.Matrix(scale, scale), alpha=False)
            pix.save(str(out))
        return out
    except Exception:
        return None


def picture(slide, name: str, left: float, top: float, width: float) -> bool:
    """Place a rasterised SVG. False when the artwork could not be produced."""
    png = svg_png(name)
    if not png:
        return False
    slide.shapes.add_picture(str(png), Inches(left), Inches(top), width=Inches(width))
    return True


# --------------------------------------------------------------------------
# Primitives
# --------------------------------------------------------------------------

def node(slide, left, top, width, height, title, sub="", *,
         fill=PAPER_ALT, accent=CYAN, title_color=INK, sub_color=MUTED,
         title_size=11.5, sub_size=8.5):
    """A labelled box with an accent edge. The unit every diagram is built from."""
    _rect(slide, left, top, width, height, fill)
    _rect(slide, left, top, width, 0.045, accent)
    _text(slide, left + 0.1, top + 0.16, width - 0.2, 0.32, title,
          size=title_size, bold=True, color=title_color)
    if sub:
        _text(slide, left + 0.1, top + 0.5, width - 0.2, height - 0.58, sub,
              size=sub_size, color=sub_color)


def connector(slide, x1, y1, x2, y2, *, color=CYAN, width=1.5, dashed=False):
    """
    A straight line between two points, in inches.

    Drawn with a connector shape rather than a thin rectangle so it survives
    being moved in PowerPoint by whoever edits the deck next — a rectangle
    rotated to look like a diagonal stops being a line the moment anything
    around it is nudged.
    """
    from pptx.util import Emu
    conn = slide.shapes.add_connector(
        1,  # straight
        Inches(x1), Inches(y1), Inches(x2), Inches(y2),
    )
    conn.line.color.rgb = _rgb(color)
    conn.line.width = Pt(width)
    if dashed:
        from pptx.enum.dml import MSO_LINE_DASH_STYLE
        conn.line.dash_style = MSO_LINE_DASH_STYLE.DASH
    return conn


def chip(slide, left, top, width, text, *, fill=CYAN, color=PAPER, size=8.5):
    """A small pill used to label a connection."""
    _rect(slide, left, top, width, 0.26, fill, radius=True)
    _text(slide, left, top + 0.03, width, 0.22, text, size=size, bold=True,
          color=color, align=PP_ALIGN.CENTER)


# --------------------------------------------------------------------------
# Figures
# --------------------------------------------------------------------------

def architecture_map(slide, top=1.75):
    """
    The whole system on one slide.

    Laid out as three bands because that is the actual topology: things people
    touch, the things that hold state, and the hardware. The broker sits in the
    middle on purpose — it is the only path between the top two bands and the
    bottom one, and drawing it anywhere else makes the fleet look reachable by
    routes that do not exist.

    The geometry is tight on purpose and was arrived at by rendering it: the
    first version was drawn on comfortable spacing and ran off the bottom of the
    slide, straight through its own caption and the footer. python-pptx will
    happily place a shape past the slide edge and report success.
    """
    band_h = 0.82
    fleet_h = 0.68
    y1 = top                       # clients
    y2 = y1 + 1.28                 # state
    y3 = y2 + 1.24                 # broker
    y4 = y3 + 1.16                 # fleet

    def band_label(y, text):
        _text(slide, 0.85, y - 0.24, 5.0, 0.2, text, size=8, bold=True, color=MUTED)

    # --- clients -----------------------------------------------------------
    band_label(y1, "WHAT PEOPLE TOUCH")
    node(slide, 0.85, y1, 3.5, band_h, "Website \u00b7 shop \u00b7 console", "src/ \u00b7 Next.js 16 on Vercel")
    node(slide, 4.6, y1, 3.5, band_h, "Mobile app", "mobile/ \u00b7 Expo \u00b7 Play Store", accent=VIOLET)
    node(slide, 8.35, y1, 4.1, band_h, "Admin", "src/app/admin \u00b7 same deployment")

    # --- services ----------------------------------------------------------
    band_label(y2, "WHAT HOLDS STATE")
    node(slide, 0.85, y2, 3.5, band_h, "Neon Postgres", "shop \u00b7 orders \u00b7 customers", accent=VIOLET)
    node(slide, 4.6, y2, 3.5, band_h, "Control plane", "platform/ \u00b7 Express \u00b7 api.circuvent.com")
    node(slide, 8.35, y2, 4.1, band_h, "Postgres 16", "devices \u00b7 telemetry \u00b7 automations", accent=VIOLET)

    # --- broker ------------------------------------------------------------
    _rect(slide, 4.6, y3, 3.5, 0.72, INK_DEEP)
    _rect(slide, 4.6, y3, 3.5, 0.05, CYAN_BRIGHT)
    _text(slide, 4.7, y3 + 0.12, 3.3, 0.28, "Mosquitto broker", size=11, bold=True, color=PAPER)
    _text(slide, 4.7, y3 + 0.42, 3.3, 0.24, "1883 private \u00b7 8883 TLS", size=8, color="94A3B8")

    # --- fleet -------------------------------------------------------------
    band_label(y4, "WHAT PHYSICALLY HAPPENS")
    node(slide, 0.85, y4, 3.5, fleet_h, "ESP32 boards", "firmware/ \u00b7 in customers' homes")
    node(slide, 4.6, y4, 3.5, fleet_h, "Cameras", "binary frames over MQTT", accent=VIOLET)
    node(slide, 8.35, y4, 4.1, fleet_h, "Local bus", "ESP-NOW, board to board", accent=CYAN_BRIGHT)

    # --- edges -------------------------------------------------------------
    for x in (2.6, 6.35, 10.4):
        connector(slide, x, y1 + band_h, x, y2, color=SLATE, width=1.25)
    connector(slide, 6.35, y2 + band_h, 6.35, y3, color=CYAN, width=2)
    connector(slide, 6.35, y3 + 0.72, 6.35, y4, color=CYAN, width=2)

    # The local bus is the one edge that does not pass through the broker, so
    # it is routed *under* the band rather than straight across it. Drawn as a
    # straight line it passed through the middle of the camera box, which read
    # as the cameras being part of the link rather than as two boards talking
    # past them.
    y_bus = y4 + fleet_h + 0.14
    connector(slide, 2.6, y4 + fleet_h, 2.6, y_bus, color=CYAN_BRIGHT, width=2, dashed=True)
    connector(slide, 2.6, y_bus, 10.4, y_bus, color=CYAN_BRIGHT, width=2, dashed=True)
    connector(slide, 10.4, y4 + fleet_h, 10.4, y_bus, color=CYAN_BRIGHT, width=2, dashed=True)

def topic_tree(slide, left=0.9, top=1.95):
    """
    The MQTT namespace, drawn as the tree it is.

    A table of four topics reads as four unrelated facts. Drawn, the shape of
    the contract is immediate: everything hangs off one device id, and exactly
    one branch points the other way.

    The trunk is one continuous line rather than a stub per leaf. The first
    version drew separate elbows and the result did not read as a hierarchy at
    all — four boxes with hooks beside them, which is worse than the table it
    replaced.
    """
    root_h = 0.6
    _rect(slide, left, top, 3.0, root_h, INK_DEEP)
    _text(slide, left + 0.12, top + 0.15, 2.8, 0.3, "cv/<device-id>/", size=12.5,
          bold=True, color=PAPER)

    rows = [
        ("state", "device \u2192 cloud", "retained",
         "everything it currently reports", CYAN),
        ("telemetry", "device \u2192 cloud", "not retained",
         "readings worth keeping history for", CYAN),
        ("cmd", "cloud \u2192 device", "QoS 1",
         "the only topic a device subscribes to", VIOLET),
        ("status", "broker publishes", "last will",
         "how the fleet learns a device died", SLATE),
    ]

    trunk_x = left + 0.4
    row_gap = 0.72
    first = top + root_h + 0.28
    last_centre = first + row_gap * (len(rows) - 1) + 0.25

    # One trunk, drawn before the branches so the leaves sit on top of it.
    connector(slide, trunk_x, top + root_h, trunk_x, last_centre, color=SLATE, width=1.5)

    y = first
    for leaf, direction, delivery, purpose, colour in rows:
        centre = y + 0.25
        connector(slide, trunk_x, centre, left + 1.05, centre, color=SLATE, width=1.5)
        node(slide, left + 1.05, y, 2.0, 0.5, leaf, accent=colour, title_size=11)
        _text(slide, left + 3.25, centre - 0.11, 2.0, 0.24, direction, size=9.5, color=SLATE)
        chip(slide, left + 5.4, centre - 0.13, 1.5, delivery, fill=colour)
        _text(slide, left + 7.15, centre - 0.11, 4.3, 0.24, purpose, size=9.5, color=MUTED)
        y += row_gap


def cert_chains(slide, top=2.0):
    """
    Three chains side by side, because the point is the comparison.

    Two of these renew themselves and one does not, and that difference is
    invisible in prose — everybody reads "Let's Encrypt" three times and stops
    paying attention before reaching the one that is ours.
    """
    cols = [
        ("circuvent.com", ["Leaf", "Let's Encrypt R-series", "ISRG Root X1"],
         "Vercel renews it", CYAN, False),
        ("api.circuvent.com", ["Leaf", "Let's Encrypt R-series", "ISRG Root X1"],
         "Caddy renews it", CYAN, False),
        ("mqtt :8883", ["Leaf", "Circuvent CA", "embedded in firmware"],
         "Nobody renews it but us", VIOLET, True),
    ]
    x = 0.9
    for title, chain, note, colour, ours in cols:
        _text(slide, x, top, 3.6, 0.3, title, size=12.5, bold=True, color=INK)
        y = top + 0.45
        for i, link in enumerate(chain):
            node(slide, x, y, 3.6, 0.6, link,
                 accent=colour if i == len(chain) - 1 else SLATE, title_size=10.5)
            if i < len(chain) - 1:
                connector(slide, x + 1.8, y + 0.6, x + 1.8, y + 0.82, color=SLATE, width=1.25)
            y += 0.82
        chip(slide, x, y + 0.05, 3.6, note, fill=VIOLET if ours else SLATE)
        if ours:
            _text(slide, x, y + 0.45, 3.6, 0.75,
                  "Replace this and every device must take an OTA first, in that "
                  "order, or the fleet cannot reconnect.",
                  size=8.5, color=MUTED)
        x += 3.95


def home_plan(slide, top=1.95):
    """
    A 3BHK, and the two ways a switch can reach a light.

    This is the slide that earns the local bus. The rooms are drawn to scale
    with each other rather than accurately — what matters is that the boards are
    in different rooms, that the solid path leaves the building and comes back,
    and that the dashed one does not.
    """
    rooms = [
        ("Hall", 0.9, 2.55),
        ("Bedroom 1", 3.6, 2.05),
        ("Bedroom 2", 5.8, 2.05),
        ("Bedroom 3", 8.0, 2.05),
        ("Kitchen", 10.2, 2.25),
    ]
    for name, x, w in rooms:
        _rect(slide, x, top, w, 1.55, PAPER_ALT, line="CBD5E1")
        _text(slide, x + 0.12, top + 0.1, w - 0.24, 0.28, name, size=10, bold=True, color=INK)
        _rect(slide, x + 0.12, top + 0.5, 0.9, 0.42, INK_DEEP)
        _text(slide, x + 0.16, top + 0.57, 0.82, 0.28, "board", size=8, color=PAPER,
              align=PP_ALIGN.CENTER)
        _text(slide, x + 1.1, top + 0.55, w - 1.2, 0.6, "lights · fans", size=8, color=MUTED)

    # The local path: board to board, staying inside the flat.
    y_local = top + 1.75
    connector(slide, 1.35, top + 0.92, 1.35, y_local, color=CYAN_BRIGHT, width=2, dashed=True)
    connector(slide, 1.35, y_local, 10.55, y_local, color=CYAN_BRIGHT, width=2, dashed=True)
    for _, x, _w in rooms[1:]:
        connector(slide, x + 0.57, top + 0.92, x + 0.57, y_local, color=CYAN_BRIGHT,
                  width=2, dashed=True)
    chip(slide, 5.0, y_local + 0.12, 3.2, "ESP-NOW \u00b7 stays in the building",
         fill=CYAN_BRIGHT, color=INK_DEEP)

    # The cloud path: the same switch, the long way round.
    y_cloud = y_local + 0.75
    node(slide, 0.9, y_cloud, 2.4, 0.62, "Router", "", accent=SLATE, title_size=10)
    node(slide, 3.6, y_cloud, 2.4, 0.62, "Internet", "", accent=SLATE, title_size=10)
    node(slide, 6.3, y_cloud, 2.4, 0.62, "Broker", "", accent=SLATE, title_size=10)
    node(slide, 9.0, y_cloud, 3.45, 0.62, "back down to the next room", "",
         accent=SLATE, title_size=10)
    for x in (3.3, 6.0, 8.7):
        connector(slide, x, y_cloud + 0.31, x + 0.3, y_cloud + 0.31, color=SLATE, width=1.5)
    chip(slide, 4.6, y_cloud + 0.78, 4.0, "the same tap, before the local bus",
         fill=SLATE)
    _text(slide, 0.9, y_cloud + 1.2, 11.6, 0.5,
          "Two boards two metres apart, and the command left the country and came back. "
          "That path is still there and still authoritative \u2014 it is simply no longer the only one, "
          "and no longer what a light switch waits for.",
          size=10, color=MUTED)


def deploy_pipeline(slide, top=2.0):
    """Four things, four mechanisms, drawn as four lanes."""
    lanes = [
        ("Website · console", ["git push", "Vercel build", "circuvent.com"], CYAN),
        ("Control plane", ["ssh to VM", "docker compose up -d --build", "api.circuvent.com"], VIOLET),
        ("Mobile", ["build-android.mjs", "signing checked twice", "Play / sideload"], CYAN),
        ("Firmware", ["platformio run", "public/fw/*.bin", "OTA over MQTT"], VIOLET),
    ]
    y = top
    for name, steps, colour in lanes:
        _text(slide, 0.9, y + 0.18, 2.5, 0.3, name, size=11, bold=True, color=INK)
        x = 3.5
        for i, step in enumerate(steps):
            node(slide, x, y, 2.75, 0.62, step, accent=colour, title_size=9.5)
            if i < len(steps) - 1:
                connector(slide, x + 2.75, y + 0.31, x + 2.95, y + 0.31, color=SLATE, width=1.5)
            x += 2.95
        y += 0.92
