import React, { useEffect, useMemo, useState } from "react";
import { Text, View } from "react-native";
import { Card, EmptyState, useTheme } from "../../../ui";
import { ActionButton, Callout, CapacityBar, MetricRow, Pill, SeverityBadge } from "../../../enterprise-ui";
import { Legend, MultiLineChart } from "../../../charts";
import { api } from "../../../api";
import { loadEnergySeries, useZones } from "./useZones";
import { asBoolean, commandForToggle } from "./fields";
import { DeviceHeader, ModuleScaffold } from "./parts";

const BANDS = [{ max: 50, label: "Good", sev: "success" }, { max: 100, label: "Moderate", sev: "info" }, { max: 150, label: "Unhealthy for sensitive groups", sev: "warning" }, { max: 200, label: "Unhealthy", sev: "warning" }, { max: 300, label: "Very unhealthy", sev: "critical" }, { max: Infinity, label: "Hazardous", sev: "critical" }] as const;
function band(v: number) { return BANDS.find((b)=>v<=b.max) ?? BANDS[BANDS.length-1]; }
function threshold(label: string, settings: any) { if (label === "AQI") return settings.aqi; if (label === "PM2.5") return settings.pm25; if (label === "PM10") return settings.pm10; if (label === "CO₂") return settings.co2; return settings.voc; }
export function AirQuality({ onBack }: { onBack: () => void }) { const { c }=useTheme(); const z=useZones(); const [busy,setBusy]=useState<string|null>(null); const devices=useMemo(()=>z.data?.devices.filter((d)=>z.data!.fieldMap[d.id].capabilities.includes("air"))??[],[z.data]); const createAuto=async(id:string, field:string, value:number)=>{ const d=z.data!.devices.find(x=>x.id===id)!; setBusy(`${id}-${field}`); try{ await api.createAutomation({ name:`${d.name} ${field} threshold`, enabled:true, trigger:{type:"state",deviceId:id,field,op:">=",value}, action:{type:"notify", title:"Air quality threshold", body:`${d.name} reported ${field} at or above ${value}`} }); } finally{ setBusy(null); } };
return <ModuleScaffold title="Air quality" subtitle="Real pollutant readings and history" icon="airQuality" onBack={onBack} loading={z.loading} error={z.error} onRetry={z.reload} refreshing={z.refreshing} onRefresh={z.refresh}>{!z.data||!devices.length?<EmptyState icon="airQuality" title="No air-quality readings" subtitle="Devices appear here only when AQI, PM2.5, PM10, CO₂ or VOC fields are reported."/>:devices.map((d)=>{ const f=z.data!.fieldMap[d.id]; return <Card key={d.id} style={{marginBottom:14}}><DeviceHeader device={d} fields={f}/><Callout kind="info" title="Band definition" text="AQI interpretation uses the published US EPA breakpoints: Good 0–50, Moderate 51–100, Unhealthy for sensitive groups 101–150, Unhealthy 151–200, Very unhealthy 201–300, Hazardous 301+." icon="info"/>{!f.pollutants.length?<Text style={{color:c.faint}}>No pollutant field currently has a reading.</Text>:f.pollutants.map((p)=>{ const th=threshold(p.label,z.data!.settings.air); const b=p.numeric!=null&&p.label==="AQI"?band(p.numeric):null; return <View key={p.field} style={{marginBottom:10}}><View style={{flexDirection:"row",alignItems:"center",gap:8}}><Text style={{color:c.text,fontWeight:"900",flex:1}}>{p.label}</Text>{b?<SeverityBadge severity={b.sev} label={b.label}/>:null}</View><CapacityBar value={p.numeric??0} max={Math.max(th*1.2,p.numeric??0,1)} threshold={th} label={`${p.field} threshold`} unit={p.unit}/>{p.numeric==null?<MetricRow label="Reading" value="reported field exists, latest numeric state not available"/>:null}<ActionButton label="Create threshold automation" icon="automate" outline busy={busy===`${d.id}-${p.field}`} onPress={()=>createAuto(d.id,p.field,th)}/></View>})}<AirHistory id={d.id} fields={f.pollutants.map(p=>p.field).filter(field=>f.telemetryFields.includes(field))}/>{(f.purifier||f.fan)?<ActionButton label={`${asBoolean(f.purifier??f.fan)?"Turn off":"Turn on"} purifier/fan`} icon="fanBlade" disabled={!d.online} onPress={async()=>{const p=f.purifier??f.fan!; await api.command(d.id, commandForToggle(p,!asBoolean(p))); await z.refresh();}}/>:<Pill label="No purifier or fan control field" icon="info" color={c.faint}/>}</Card>})}</ModuleScaffold>; }
function AirHistory({id,fields}:{id:string;fields:string[]}){ const {c}=useTheme(); const [series,setSeries]=useState<{name:string;color:string;data:number[]}[]>([]); useEffect(()=>{let alive=true;(async()=>{const colors=[c.violet,c.cyan,c.amber,c.green,c.red]; const out=[] as {name:string;color:string;data:number[]}[]; for(let i=0;i<fields.length;i++){const s=await loadEnergySeries(id,fields[i],48); const data=s?.series.map(p=>p.avg).filter(Number.isFinite)??[]; if(data.length) out.push({name:fields[i],color:colors[i%colors.length],data});} if(alive)setSeries(out);})();return()=>{alive=false};},[id,fields.join("|"),c.violet,c.cyan,c.amber,c.green,c.red]); if(!fields.length)return <Callout kind="info" text="No pollutant fields were present in telemetry, so history was not requested."/>; return <View><Text style={{color:c.text,fontWeight:"900",marginTop:8}}>Pollutant history</Text><MultiLineChart series={series} height={190} area unit=""/><Legend items={series.map(s=>({name:s.name,color:s.color}))}/></View>;}
