import React, { useEffect, useMemo, useState } from "react";
import { Text, View } from "react-native";
import { Card, EmptyState, useTheme, ArcGauge } from "../../../ui";
import { ActionButton, Callout, MetricRow, Pill, SelectField, Stepper } from "../../../enterprise-ui";
import { LineChart } from "../../../charts";
import { api } from "../../../api";
import { asNumber, fieldText } from "./fields";
import { loadEnergySeries, useZones, type ZoneSettings } from "./useZones";
import { DeviceHeader, ModuleScaffold } from "./parts";

const MODES = ["cool","heat","dry","fan","auto","off"] as const; const SPEEDS=["low","medium","high","auto"] as const;
export function ClimateControl({onBack}:{onBack:()=>void}){ const {c}=useTheme(); const z=useZones(); const devices=useMemo(()=>z.data?.devices.filter(d=>z.data!.fieldMap[d.id].capabilities.includes("climate"))??[],[z.data]); const [pending,setPending]=useState<string|null>(null); const saveTarget=async(partial:Partial<ZoneSettings["climate"]>)=>{if(!z.data)return; await z.saveSettings({...z.data.settings, climate:{...z.data.settings.climate,...partial}})};
return <ModuleScaffold title="Climate control" subtitle="HVAC and comfort targets from real fields" icon="hvac" onBack={onBack} loading={z.loading} error={z.error} onRetry={z.reload} refreshing={z.refreshing} onRefresh={z.refresh}>{!z.data||!devices.length?<EmptyState icon="hvac" title="No HVAC-capable devices" subtitle="Devices appear here when they report temperature, humidity, setpoint, HVAC mode or fan-speed fields."/>:<>
<Card style={{marginBottom:14}}><Text style={{color:c.text,fontWeight:"900",fontSize:16}}>Local comfort target</Text><Text style={{color:c.faint,marginBottom:10}}>Operator-entered preference used only for display and alerting on this device.</Text><Stepper label="Target temperature" value={z.data.settings.climate.temperature} min={10} max={35} step={1} unit="°C" onChange={(temperature)=>saveTarget({temperature})}/><Stepper label="Target humidity" value={z.data.settings.climate.humidity} min={20} max={80} step={1} unit="%" onChange={(humidity)=>saveTarget({humidity})}/></Card>
{devices.map(d=>{const f=z.data!.fieldMap[d.id]; const temp=asNumber(f.temperature); const hum=asNumber(f.humidity); const sp=asNumber(f.setpoint); return <Card key={d.id} style={{marginBottom:14}}><DeviceHeader device={d} fields={f}/>{sp!=null?<ArcGauge value={sp} min={16} max={32} unit="°C" caption="Reported setpoint" onChange={async(v)=>{ if(!f.setpoint)return; setPending(d.id); try{ await api.command(d.id,{[f.setpoint.field]:v, field:f.setpoint.field, value:v, action:"set"}); await z.refresh(); } finally{ setPending(null); } }}/>:<Callout kind="info" text="This device does not report a setpoint field, so no dial is shown."/>}<MetricRow icon="temperature" label="Current temperature" value={fieldText(f.temperature,1)}/><MetricRow icon="humidity" label="Current humidity" value={fieldText(f.humidity,0)}/><MetricRow icon="tune" label="Reported setpoint" value={fieldText(f.setpoint,1)}/>{temp!=null?<Pill label={`${Math.abs(temp-z.data!.settings.climate.temperature).toFixed(1)}°C from target`} icon={Math.abs(temp-z.data!.settings.climate.temperature)>2?"warning":"success"} color={Math.abs(temp-z.data!.settings.climate.temperature)>2?c.amber:c.green}/>:null}{hum!=null?<Pill label={`${Math.abs(hum-z.data!.settings.climate.humidity).toFixed(0)}% humidity delta`} icon={Math.abs(hum-z.data!.settings.climate.humidity)>10?"warning":"success"} color={Math.abs(hum-z.data!.settings.climate.humidity)>10?c.amber:c.green}/>:null}{f.mode?<SelectField label="Mode" value={String(f.mode.value)} options={MODES.map(m=>({value:m,label:m}))} onChange={async(mode)=>{setPending(d.id); try{await api.command(d.id,{[f.mode!.field]:mode, field:f.mode!.field, value:mode, action:"set"}); await z.refresh();}finally{setPending(null)}}}/>:<MetricRow icon="tune" label="Mode" value="not reported"/>}{f.fanSpeed?<SelectField label="Fan speed" value={String(f.fanSpeed.value)} options={SPEEDS.map(m=>({value:m,label:m}))} onChange={async(speed)=>{setPending(d.id); try{await api.command(d.id,{[f.fanSpeed!.field]:speed, field:f.fanSpeed!.field, value:speed, action:"set"}); await z.refresh();}finally{setPending(null)}}}/>:<MetricRow icon="fanBlade" label="Fan speed" value="not reported"/>}{pending===d.id?<Text style={{color:c.faint}}>Command sent; waiting for the next reported device state.</Text>:null}<ClimateHistory id={d.id} fields={[f.temperature?.field,f.humidity?.field].filter(Boolean) as string[]} telemetry={f.telemetryFields}/></Card>})}</>}</ModuleScaffold>}
function ClimateHistory({id,fields,telemetry}:{id:string;fields:string[];telemetry:string[]}){ const {c}=useTheme(); const [series,setSeries]=useState<Record<string,number[]>>({}); useEffect(()=>{let alive=true;(async()=>{const out:Record<string,number[]>={}; for(const f of fields){ if(!telemetry.includes(f)) continue; const s=await loadEnergySeries(id,f,48); out[f]=s?.series.map(p=>p.avg).filter(Number.isFinite)??[];} if(alive)setSeries(out);})(); return()=>{alive=false};},[id,fields.join("|"),telemetry.join("|")]); return <View>{fields.map((f)=><View key={f}><Text style={{color:c.text,fontWeight:"800",marginTop:8}}>{f} history</Text>{telemetry.includes(f)?<LineChart data={series[f]??[]} color={f.toLowerCase().includes("hum")?c.cyan:c.amber}/>:<Callout kind="info" text={`${f} is not present in telemetry; history was not requested.`}/>}</View>)}</View> }
