import React, { useEffect, useMemo, useState } from "react";
import { Text, View } from "react-native";
import { Card, EmptyState, useTheme } from "../../../ui";
import { BarChart, CalendarHeatmap, HBars } from "../../../charts";
import { Callout, MetricRow, Stepper } from "../../../enterprise-ui";
import { bucketSeries, formatRelative } from "../../../enterprise";
import { asBoolean } from "./fields";
import { loadTelemetryRows, roomNameOf, useZones, type ZoneSettings } from "./useZones";
import { DeviceHeader, ModuleScaffold } from "./parts";

type Hist={hourly:number[];days:{date:string;value:number}[];last?:string;count:number;busiest:string};
function active(v:any){ if(typeof v==="boolean")return v; if(typeof v==="number")return v>0; if(typeof v==="string")return ["1","true","on","detected","occupied","active"].includes(v.toLowerCase()); return false; }
export function OccupancyInsights({onBack}:{onBack:()=>void}){ const {c}=useTheme(); const z=useZones(120); const devices=useMemo(()=>z.data?.devices.filter(d=>z.data!.fieldMap[d.id].capabilities.includes("occupancy"))??[],[z.data]); const [hist,setHist]=useState<Record<string,Hist>>({}); useEffect(()=>{let alive=true;(async()=>{if(!z.data)return; const out:Record<string,Hist>={}; for(const d of devices){const f=z.data.fieldMap[d.id]; const field=f.motion?.field??f.occupancy?.field; if(!field)continue; const rows=await loadTelemetryRows(d.id,500); const events=rows.filter(r=>active(r.payload?.[field])).map(r=>new Date(r.ts).getTime()).filter(Number.isFinite); const hourly=Array.from({length:24},()=>0); const daysMap=new Map<string,number>(); for(const t of events){const dt=new Date(t); hourly[dt.getHours()]++; const key=dt.toISOString().slice(0,10); daysMap.set(key,(daysMap.get(key)??0)+1);} const busiest=hourly.reduce((best,v,i)=>v>hourly[best]?i:best,0); out[d.id]={hourly,days:[...daysMap.entries()].sort().slice(-42).map(([date,value])=>({date,value})),last:events.length?new Date(Math.max(...events)).toISOString():undefined,count:events.length,busiest:events.length?`${busiest}:00–${busiest+1}:00`:"no activity"}; } if(alive)setHist(out);})(); return()=>{alive=false};},[z.data,devices]); const saveVacancy=async(minutes:number)=>{if(!z.data)return; const next:ZoneSettings={...z.data.settings,vacancy:{minutes}}; await z.saveSettings(next)}; const roomBars=useMemo(()=>{if(!z.data)return[]; const m=new Map<string,number>(); for(const d of devices)m.set(roomNameOf(d),(m.get(roomNameOf(d))??0)+(hist[d.id]?.count??0)); return [...m.entries()].map(([name,value])=>({name,value,color:c.accent}));},[z.data,devices,hist,c.accent]); const vacant=useMemo(()=>{if(!z.data)return[]; const cutoff=Date.now()-z.data.settings.vacancy.minutes*60000; const byRoom=new Map<string,number>(); for(const d of devices){const h=hist[d.id]; if(!h?.last)continue; const t=new Date(h.last).getTime(); byRoom.set(roomNameOf(d),Math.max(byRoom.get(roomNameOf(d))??0,t));} return [...byRoom.entries()].filter(([,t])=>t<cutoff).map(([name,t])=>({name,t}));},[z.data,devices,hist]);
return <ModuleScaffold title="Occupancy insights" subtitle="Motion history from real telemetry timestamps" icon="motion" onBack={onBack} loading={z.loading} error={z.error} onRetry={z.reload} refreshing={z.refreshing} onRefresh={z.refresh}>{!z.data||!devices.length?<EmptyState icon="motion" title="No occupancy devices" subtitle="Motion or occupancy devices appear here only when real fields are reported."/>:<><Card style={{marginBottom:14}}><Text style={{color:c.text,fontWeight:"900"}}>Vacancy window</Text><Stepper label="Mark vacant after" value={z.data.settings.vacancy.minutes} min={5} max={1440} step={5} unit="min" onChange={saveVacancy}/>{vacant.map(v=><Callout key={v.name} kind="info" title={`${v.name} appears vacant`} text={`No motion since ${formatRelative(new Date(v.t))}, beyond your ${z.data!.settings.vacancy.minutes} minute window.`} icon="empty"/> )}</Card><Card style={{marginBottom:14}}><Text style={{color:c.text,fontWeight:"900",marginBottom:8}}>Per-room occupancy comparison</Text><HBars items={roomBars} unit=" events"/></Card>{devices.map(d=>{const f=z.data!.fieldMap[d.id]; const h=hist[d.id]; return <Card key={d.id} style={{marginBottom:14}}><DeviceHeader device={d} fields={f}/><MetricRow icon="motion" label="Current motion" value={f.motion? (asBoolean(f.motion)?"active":"clear") : "not reported"}/><MetricRow icon="users" label="Current occupancy" value={f.occupancy? (asBoolean(f.occupancy)?"occupied":"vacant") : "not reported"}/><MetricRow icon="clock" label="Last triggered" value={h?.last?formatRelative(h.last):"no telemetry trigger in observation window"}/><MetricRow icon="history" label="Observation window" value="last 500 telemetry rows"/><Text style={{color:c.text,fontWeight:"900",marginTop:8}}>Hourly activity</Text><BarChart data={bucketSeries((h?.hourly??[]).map((v,i)=>({t:i,v})),24).map(p=>p.v)} color={c.violet}/><MetricRow label="Busiest hour" value={h?.busiest??"no activity"}/><Text style={{color:c.text,fontWeight:"900",marginTop:8}}>Daily activity</Text><CalendarHeatmap days={h?.days??[]}/></Card>})}</>}</ModuleScaffold>}
