import React, { useEffect, useMemo, useState } from "react";
import { View, Text } from "react-native";
import { Card, EmptyState, useTheme } from "../../../ui";
import { ActionButton, BottomSheet, Callout, CapacityBar, Kpi, KpiGrid, MetricRow, Stepper, ToggleField } from "../../../enterprise-ui";
import { LineChart } from "../../../charts";
import { api } from "../../../api";
import { numericSeries, statsOf, formatRelative } from "../../../enterprise";
import { asBoolean, asNumber, commandForToggle, fieldText } from "./fields";
import { loadEnergySeries, loadTelemetryRows, tankConfig, useZones, type ZoneSettings } from "./useZones";
import { DeviceHeader, ModuleScaffold } from "./parts";
import { TankSvg } from "./TankSvg";

export function WaterTank({ onBack }: { onBack: () => void }) {
  const { c } = useTheme(); const z = useZones(); const [edit, setEdit] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null);
  const tanks = useMemo(() => z.data?.devices.filter((d) => z.data!.fieldMap[d.id].capabilities.includes("tank")) ?? [], [z.data]);
  const saveTank = async (id: string, cfg: ReturnType<typeof tankConfig>) => { if (!z.data) return; const next: ZoneSettings = { ...z.data.settings, tanks: { ...z.data.settings.tanks, [id]: cfg } }; await z.saveSettings(next); };
  const createAutomation = async (id: string) => { if (!z.data) return; const f = z.data.fieldMap[id]; if (!f.level || !f.pump) return; const cfg = tankConfig(z.data.settings, id); setBusy(id); try { await api.createAutomation({ name: `${f.device.name} auto-fill on below ${cfg.onBelow}%`, enabled: true, trigger: { type: "state", deviceId: id, field: f.level.field, op: "<", value: cfg.onBelow }, action: { type: "command", deviceId: id, command: commandForToggle(f.pump, true) } }); await api.createAutomation({ name: `${f.device.name} stop fill above ${cfg.offAbove}%`, enabled: true, trigger: { type: "state", deviceId: id, field: f.level.field, op: ">=", value: cfg.offAbove }, action: { type: "command", deviceId: id, command: commandForToggle(f.pump, false) } }); } finally { setBusy(null); } };
  return <ModuleScaffold title="Water tanks" subtitle="Measured tank levels and pump controls" icon="watertank" onBack={onBack} loading={z.loading} error={z.error} onRetry={z.reload} refreshing={z.refreshing} onRefresh={z.refresh}>
    {!z.data || !tanks.length ? <EmptyState icon="watertank" title="No tank readings" subtitle="A water tank device appears here only when it reports a real level field in state or telemetry." /> : tanks.map((d) => { const f = z.data!.fieldMap[d.id]; const level = asNumber(f.level); const cfg = tankConfig(z.data!.settings, d.id); const litres = level == null ? undefined : (cfg.capacityL * level) / 100; return <Card key={d.id} style={{ marginBottom: 14 }}><DeviceHeader device={d} fields={f}/>
      {level == null ? <Callout kind="warning" title="Level not reported" text="This device is tank-capable but does not currently report a numeric level. No fill percentage or litres are shown." icon="warning"/> : <View style={{ alignItems: "center" }}><TankSvg level={level} label={d.name}/><Text style={{ color: c.faint, textAlign: "center" }}>{litres?.toFixed(0)} L calculated from your entered {cfg.capacityL} L tank capacity.</Text></View>}
      <KpiGrid><Kpi icon="tank" label="Reported level" value={level == null ? "no reading" : level.toFixed(0)} unit={level == null ? undefined : "%"}/><Kpi icon="storage" label="Calculated volume" value={litres == null ? "no reading" : litres.toFixed(0)} unit={litres == null ? undefined : "L"} footnote="Calculated from entered tank dimensions"/><Kpi icon="clock" label="Last seen" value={d.last_seen ? formatRelative(d.last_seen) : "never"}/></KpiGrid>
      <MetricRow icon="trigger" label="Level field" value={f.level?.field ?? "not reported"}/><MetricRow icon="power" label="Pump state" value={f.pump ? fieldText(f.pump) : "device does not report a pump/relay field"}/><MetricRow icon="shield" label="Dry-run protection" value={f.dryRun ? fieldText(f.dryRun) : "device does not report dry-run protection"}/>
      {f.pump ? <ToggleField label="Pump control" help="Sends a command to the real pump/relay field. The displayed state remains the device-reported state." value={!!asBoolean(f.pump)} onChange={async (v)=>{ setBusy(d.id); try { await api.command(d.id, commandForToggle(f.pump!, v)); await z.refresh(); } finally { setBusy(null); } }} icon="power" disabled={busy===d.id || !d.online}/> : null}
      <CapacityBar value={level ?? 0} max={100} threshold={cfg.onBelow} label="Auto-fill on below threshold" unit="%" tint={c.cyan}/><CapacityBar value={level ?? 0} max={100} threshold={cfg.offAbove} label="Auto-fill off above threshold" unit="%" tint={c.green}/>
      <TankHistory deviceId={d.id} field={f.level?.field} telemetryFields={f.telemetryFields}/>
      <View style={{ flexDirection: "row", gap: 10 }}><ActionButton label="Tank settings" icon="settings" outline onPress={()=>setEdit(d.id)}/><ActionButton label="Create automations" icon="automate" busy={busy===d.id} disabled={!f.level || !f.pump} onPress={()=>createAutomation(d.id)}/></View>
      {edit===d.id ? <TankSheet cfg={cfg} onClose={()=>setEdit(null)} onSave={(next)=>{ saveTank(d.id,next); setEdit(null); }}/> : null}
    </Card>; })}
  </ModuleScaffold>;
}

function TankHistory({ deviceId, field, telemetryFields }: { deviceId: string; field?: string; telemetryFields: string[] }) { const { c } = useTheme(); const [vals, setVals] = useState<number[]>([]); const [rate, setRate] = useState<string>("not enough samples"); useEffect(()=>{ let alive=true; (async()=>{ if (!field || !telemetryFields.includes(field)) { setVals([]); return; } const [energy, rows] = await Promise.all([loadEnergySeries(deviceId, field, 48), loadTelemetryRows(deviceId, 200)]); if (!alive) return; setVals(energy?.series.map((p)=>p.avg).filter(Number.isFinite) ?? []); const pts = numericSeries(rows, field); const st = statsOf(pts); if (pts.length>=2) { const a=pts[pts.length-2], b=pts[pts.length-1]; const hours=(b.t-a.t)/3600000; setRate(hours>0 ? `${((b.v-a.v)/hours).toFixed(1)} %/h over ${(hours*60).toFixed(0)} min sample interval` : "sample interval unavailable"); } else setRate(st.count ? "only one real sample" : "no real samples"); })(); return()=>{alive=false}; },[deviceId, field, telemetryFields]); if (!field) return <Callout kind="info" text="No level field exists, so history is unavailable."/>; if (!telemetryFields.includes(field)) return <Callout kind="info" text={`Field ${field} is present in state but not in telemetry; history is not requested.`}/>; return <View><Text style={{ color: c.text, fontWeight: "900", marginTop: 10 }}>Level history</Text><LineChart data={vals} color={c.cyan}/><MetricRow icon="trendUp" label="Fill/drain rate" value={rate}/></View>; }
function TankSheet({ cfg, onSave, onClose }: { cfg: ReturnType<typeof tankConfig>; onSave: (v: ReturnType<typeof tankConfig>)=>void; onClose:()=>void }) { const [v,setV]=useState(cfg); return <BottomSheet visible onClose={onClose} title="Tank geometry and thresholds" footer={<ActionButton label="Save tank settings" icon="save" onPress={()=>onSave(v)}/> }><Stepper label="Capacity" value={v.capacityL} min={1} max={100000} step={50} unit="L" onChange={(capacityL)=>setV({...v,capacityL})} help="Operator-entered capacity; volumes are calculated from this value."/><Stepper label="Sensor offset" value={v.sensorOffsetCm} min={0} max={500} step={1} unit="cm" onChange={(sensorOffsetCm)=>setV({...v,sensorOffsetCm})}/><Stepper label="Turn pump on below" value={v.onBelow} min={0} max={100} step={1} unit="%" onChange={(onBelow)=>setV({...v,onBelow})}/><Stepper label="Turn pump off above" value={v.offAbove} min={0} max={100} step={1} unit="%" onChange={(offAbove)=>setV({...v,offAbove})}/></BottomSheet>; }
