import React, { useCallback, useEffect, useState } from "react";
import { ScrollView, Switch, Text, TextInput, View } from "react-native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { registerForPush } from "../../push";
import { Banner, Card, IconButton, ListRow, Screen, SectionLabel, Title, useTheme } from "../../ui";
const KEY="cv-notification-settings-v1";
type Prefs={critical:boolean; device:boolean; energy:boolean; marketing:boolean; push:boolean; quietStart:string; quietEnd:string};
const def:Prefs={critical:true,device:true,energy:true,marketing:false,push:false,quietStart:"22:00",quietEnd:"07:00"};
export default function NotificationSettings({ onBack }: { onBack: () => void }) { const { c }=useTheme(); const [p,setP]=useState<Prefs>(def); const [msg,setMsg]=useState(""); useEffect(()=>{AsyncStorage.getItem(KEY).then(v=>v&&setP({...def,...JSON.parse(v)})).catch(()=>{});},[]); const save=useCallback((n:Prefs)=>{setP(n); AsyncStorage.setItem(KEY,JSON.stringify(n)).catch(()=>{});},[]); const set=(k:keyof Prefs,v:boolean|string)=>save({...p,[k]:v}); const enablePush=async(v:boolean)=>{ if(v){const t=await registerForPush(); setMsg(t?"Push enabled for this device.":"Push permission unavailable; preferences saved locally.");} set("push",v);}; return <Screen><ScrollView contentContainerStyle={{padding:16,paddingTop:56,paddingBottom:90}}><View style={{flexDirection:"row",alignItems:"center",gap:12,marginBottom:16}}><IconButton glyph="‹" onPress={onBack}/><Title>Notifications</Title></View>{msg?<Banner kind="info" text={msg}/>:null}<SectionLabel>Alert types</SectionLabel><Card style={{marginBottom:14}}>{([["critical","Critical alerts"],["device","Device offline/online"],["energy","Energy insights"],["marketing","Product tips"]] as const).map(([k,t])=><ListRow key={k} icon="🔔" title={t} subtitle={k==="critical"?"Safety and security notices":"Stored locally on this device"} right={<Switch value={Boolean(p[k])} onValueChange={v=>set(k,v)}/>}/>)}</Card><SectionLabel>Push & quiet hours</SectionLabel><Card><ListRow icon="📲" title="Enable push" subtitle="Best-effort Expo push registration" right={<Switch value={p.push} onValueChange={enablePush}/>}/><View style={{flexDirection:"row",gap:10,marginTop:8}}><TextInput value={p.quietStart} onChangeText={v=>set("quietStart",v)} style={{flex:1,color:c.text,borderWidth:1,borderColor:c.borderHi,borderRadius:12,padding:12}}/><TextInput value={p.quietEnd} onChangeText={v=>set("quietEnd",v)} style={{flex:1,color:c.text,borderWidth:1,borderColor:c.borderHi,borderRadius:12,padding:12}}/></View><Text style={{color:c.faint,marginTop:8}}>Quiet hours use 24-hour HH:MM time.</Text></Card></ScrollView></Screen>; }
