import React, { useCallback, useEffect, useMemo, useState } from "react";
import { ScrollView, Switch, Text, TextInput, View } from "react-native";
import { api, Automation } from "../../api";
import { CalendarHeatmap } from "../../charts";
import { capabilities, useDevices } from "../../store";
import { Banner, Card, EmptyState, IconButton, ListRow, PrimaryButton, Screen, SectionLabel, SegmentedControl, Title, useTheme } from "../../ui";

type Cmd = "on" | "off";
const timeOk = (s: string) => /^([01]\d|2[0-3]):[0-5]\d$/.test(s);
export default function Schedules({ onBack }: { onBack: () => void }) {
  const { c } = useTheme(); const { devices } = useDevices(); const [items, setItems] = useState<Automation[]>([]); const [busy, setBusy] = useState(false); const [deviceId, setDeviceId] = useState(""); const [time, setTime] = useState("07:00"); const [cmd, setCmd] = useState<Cmd>("on"); const [err, setErr] = useState("");
  const load = useCallback(async () => { const r = await api.automations(); if (r.ok) setItems((r.data.automations || []).filter((a) => a.trigger?.type === "time")); }, []);
  useEffect(() => { load(); }, [load]); useEffect(() => { if (!deviceId && devices[0]) setDeviceId(devices[0].id); }, [deviceId, devices]);
  const selected = devices.find((d) => d.id === deviceId); const heat = useMemo(() => Array.from({ length: 35 }, (_, i) => { const d = new Date(); d.setDate(d.getDate() - (34 - i)); return { date: d.toISOString().slice(0,10), value: i > 27 ? items.length : 0 }; }), [items.length]);
  const create = async () => { if (!selected) return setErr("Add a device before creating schedules."); if (!timeOk(time)) return setErr("Use 24-hour HH:MM time."); setBusy(true); setErr(""); const cap = capabilities(selected.type); const field = cap.power?.field || "power"; const command = { action: "set", [field]: cmd === "on" }; const r = await api.createAutomation({ name: `${selected.name} ${cmd} at ${time}`, trigger: { type: "time", at: time }, action: { type: "command", deviceId: selected.id, command } }); if (!r.ok) setErr("Could not create schedule."); await load(); setBusy(false); };
  const toggle = async (a: Automation) => { await api.updateAutomation(a.id, { enabled: !a.enabled }); await load(); };
  const del = async (id: number) => { await api.deleteAutomation(id); await load(); };
  return <Screen><ScrollView contentContainerStyle={{ padding: 16, paddingTop: 56, paddingBottom: 90 }}><View style={{ flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 16 }}><IconButton glyph="‹" onPress={onBack} /><Title>Schedules</Title></View>{err ? <Banner kind="error" text={err} /> : null}<SectionLabel>Create timer</SectionLabel><Card style={{ marginBottom: 16 }}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8, marginBottom: 12 }}>{devices.map((d) => <Text key={d.id} onPress={() => setDeviceId(d.id)} style={{ color: deviceId === d.id ? c.onAccent : c.textDim, backgroundColor: deviceId === d.id ? c.accent : c.cardHi, borderRadius: 999, paddingHorizontal: 12, paddingVertical: 8, overflow: "hidden" }}>{d.name}</Text>)}</ScrollView><View style={{ flexDirection: "row", gap: 10, alignItems: "center" }}><TextInput value={time} onChangeText={setTime} placeholder="HH:MM" placeholderTextColor={c.faint} style={{ flex: 1, color: c.text, borderWidth: 1, borderColor: c.borderHi, borderRadius: 12, padding: 12 }} /><View style={{ flex: 1 }}><SegmentedControl options={["on", "off"] as const} value={cmd} onChange={setCmd} /></View></View><PrimaryButton label="Create schedule" busy={busy} onPress={create} style={{ marginTop: 12 }} /></Card><SectionLabel>Upcoming activity</SectionLabel><Card style={{ marginBottom: 16 }}><CalendarHeatmap days={heat} /></Card><SectionLabel>Time automations</SectionLabel>{items.map((a) => <Card key={a.id} style={{ marginBottom: 10 }}><ListRow icon="⏱️" title={a.name} subtitle={`${a.trigger.at || "--:--"} • ${a.enabled ? "enabled" : "paused"}`} right={<View style={{ alignItems: "flex-end", gap: 8 }}><Switch value={a.enabled} onValueChange={() => toggle(a)} /><Text onPress={() => del(a.id)} style={{ color: c.red, fontWeight: "800" }}>Delete</Text></View>} /></Card>)}{!items.length ? <EmptyState glyph="⏱️" title="No schedules yet" subtitle="Create a timer automation for any connected device." /> : null}</ScrollView></Screen>;
}
