"""
Generates src/lib/report-logo.ts from the brand mark.

The logo has to reach a serverless PDF renderer, and reading it off disk at
request time is exactly how it went missing: `public/` is served statically by
the CDN and is not reliably traced into the function bundle, so the read fails
in production and succeeds on every developer's machine. A missing logo does
not throw — the header just renders without one — which is the quiet kind of
failure this codebase keeps finding.

Embedding the bytes removes the runtime dependency entirely. The cost is that
the module can go stale if the artwork changes, so `report-logo.test.ts`
re-derives it from the same source PNG and fails when the two disagree.

Run: python scripts/build_report_logo.py
"""

from __future__ import annotations

import base64
import io
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "public" / "logo-mark-160.png"
OUT = ROOT / "src" / "lib" / "report-logo.ts"

# 128px for a mark drawn at roughly 34pt. That is about 2.7x the pixels a
# 96dpi render needs, which stays crisp when the PDF is printed or zoomed,
# without carrying a 512px asset in a source file.
SIZE = 128

# Palette, not RGBA. The mark is a handful of flat brand colours, so an indexed
# PNG is about a quarter the size of the truecolour one for output that is
# indistinguishable at this scale — 6KB against 27KB, and every byte lands in a
# source file. Verified against pdf-lib's decoder rather than assumed.
COLOURS = 128


def build_png() -> bytes:
    img = Image.open(SOURCE).convert("RGBA")
    if img.size != (SIZE, SIZE):
        img = img.resize((SIZE, SIZE), Image.LANCZOS)
    img = img.quantize(colors=COLOURS, method=Image.FASTOCTREE)
    buf = io.BytesIO()
    img.save(buf, format="PNG", optimize=True)
    return buf.getvalue()


def main() -> int:
    png = build_png()
    b64 = base64.b64encode(png).decode("ascii")
    lines = [b64[i : i + 96] for i in range(0, len(b64), 96)]
    body = "\n".join(f'  "{ln}" +' for ln in lines)
    body = body.rstrip(" +")

    OUT.write_text(
        f'''/**
 * The brand mark, for the report PDFs.
 *
 * GENERATED by scripts/build_report_logo.py from public/logo-mark-160.png.
 * Do not edit by hand; run the script instead.
 *
 * Embedded rather than read from disk because `public/` is served by the CDN
 * and is not reliably traced into a serverless function bundle. A read that
 * fails there does not throw — the header simply renders without a logo, which
 * is how it went missing in the first place. `report-logo.test.ts` re-derives
 * this from the same PNG so the two cannot drift apart.
 */

/** {SIZE}x{SIZE} indexed PNG, base64. */
export const REPORT_LOGO_PNG_BASE64 =
{body};

/** Decoded bytes, ready for pdf-lib's embedPng. */
export function reportLogoBytes(): Uint8Array {{
  return Uint8Array.from(Buffer.from(REPORT_LOGO_PNG_BASE64, "base64"));
}}
''',
        encoding="utf8",
    )

    print(f"Wrote {OUT.relative_to(ROOT)}  ({len(png):,} bytes PNG -> {len(b64):,} chars base64)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
