import { Pool } from "pg";
import { config } from "./config";
import { generateSerial } from "./serial";
import { logger } from "./logger";

export const pool = new Pool({ connectionString: config.DATABASE_URL, max: 10 });

/** Create the schema on boot (idempotent). Keeps deploy to a single `up`. */
export async function initDb(): Promise<void> {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS users (
      id          BIGSERIAL PRIMARY KEY,
      email       TEXT UNIQUE NOT NULL,
      name        TEXT NOT NULL DEFAULT '',
      password    TEXT NOT NULL,
      created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS devices (
      id           TEXT PRIMARY KEY,           -- device serial / id (matches MQTT topic)
      key_hash     TEXT NOT NULL,              -- bcrypt hash of the device's claim key
      owner_id     BIGINT REFERENCES users(id) ON DELETE SET NULL,
      name         TEXT NOT NULL DEFAULT '',
      type         TEXT NOT NULL DEFAULT 'generic',
      room         TEXT NOT NULL DEFAULT '',
      online       BOOLEAN NOT NULL DEFAULT false,
      last_seen    TIMESTAMPTZ,
      state        JSONB NOT NULL DEFAULT '{}'::jsonb,
      fw_version   TEXT NOT NULL DEFAULT '',
      created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_devices_owner ON devices(owner_id);

    CREATE TABLE IF NOT EXISTS telemetry (
      id          BIGSERIAL PRIMARY KEY,
      device_id   TEXT NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
      ts          TIMESTAMPTZ NOT NULL DEFAULT now(),
      payload     JSONB NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_telemetry_device_ts ON telemetry(device_id, ts DESC);

    CREATE TABLE IF NOT EXISTS commands (
      id          BIGSERIAL PRIMARY KEY,
      device_id   TEXT NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
      user_id     BIGINT REFERENCES users(id) ON DELETE SET NULL,
      payload     JSONB NOT NULL,
      ts          TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_commands_device_ts ON commands(device_id, ts DESC);

    CREATE TABLE IF NOT EXISTS automations (
      id          BIGSERIAL PRIMARY KEY,
      owner_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      name        TEXT NOT NULL,
      enabled     BOOLEAN NOT NULL DEFAULT true,
      trigger     JSONB NOT NULL,
      action      JSONB NOT NULL,
      created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_automations_owner ON automations(owner_id);

    /*
     * Execution record, so a rule that never runs can be seen to never run.
     *
     * Switch timers spent weeks saving correctly, showing the right next-run
     * time, counting down, and never moving a relay — because the stored
     * command was a shape the device discards. Nothing in the product could
     * distinguish "fired and worked" from "never fired at all", so the fault
     * was invisible from every screen and every log a user can reach.
     *
     * last_error holds the reason a run failed rather than a boolean: "the
     * device is offline" and "you no longer own that device" need completely
     * different responses, and one undifferentiated failure flag is how
     * someone ends up reflashing firmware to chase an ownership change.
     */
    ALTER TABLE automations ADD COLUMN IF NOT EXISTS last_run_at TIMESTAMPTZ;
    ALTER TABLE automations ADD COLUMN IF NOT EXISTS last_run_ok BOOLEAN;
    ALTER TABLE automations ADD COLUMN IF NOT EXISTS last_error TEXT;
    ALTER TABLE automations ADD COLUMN IF NOT EXISTS run_count BIGINT NOT NULL DEFAULT 0;

    CREATE TABLE IF NOT EXISTS push_tokens (
      token       TEXT PRIMARY KEY,
      user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      platform    TEXT NOT NULL DEFAULT '',
      created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_push_tokens_user ON push_tokens(user_id);

    -- Which app installs are signed in to an account.
    --
    -- Support and security both need to answer "what is on this account, and
    -- from where": an old build that cannot be reproduced, a sign-in from a
    -- country the user has never visited, a phone they no longer own. None of
    -- that was answerable — push_tokens knows the platform and nothing else.
    --
    -- install_id is generated by the app and survives sign-out, so one phone
    -- stays one row rather than becoming a new one on every login.
    --
    -- Note what is *not* here: no coordinates. The app holds location
    -- permission for the weather, and reporting a user's whereabouts to staff
    -- is a different purpose from the one they granted it for — which is
    -- exactly what purpose limitation under the DPDP Act and GDPR forbids. The
    -- city columns are filled from the reverse proxy's IP geolocation when it
    -- provides one, which is what every "recent sign-ins" screen shows, and are
    -- left empty rather than guessed when it does not.
    CREATE TABLE IF NOT EXISTS app_installs (
      id           BIGSERIAL PRIMARY KEY,
      user_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      install_id   TEXT NOT NULL,
      platform     TEXT NOT NULL DEFAULT '',
      os_version   TEXT NOT NULL DEFAULT '',
      app_version  TEXT NOT NULL DEFAULT '',
      model        TEXT NOT NULL DEFAULT '',
      last_ip      TEXT NOT NULL DEFAULT '',
      last_city    TEXT NOT NULL DEFAULT '',
      last_country TEXT NOT NULL DEFAULT '',
      first_seen   TIMESTAMPTZ NOT NULL DEFAULT now(),
      last_seen    TIMESTAMPTZ NOT NULL DEFAULT now(),
      revoked_at   TIMESTAMPTZ,
      UNIQUE (user_id, install_id)
    );
    CREATE INDEX IF NOT EXISTS idx_app_installs_user ON app_installs(user_id);
    CREATE INDEX IF NOT EXISTS idx_app_installs_seen ON app_installs(last_seen DESC);

    -- Favorite flag for quick-access on the dashboard.
    ALTER TABLE devices ADD COLUMN IF NOT EXISTS favorite BOOLEAN NOT NULL DEFAULT false;

    -- Rooms: optional metadata (icon/order) + lets empty rooms exist. Device
    -- membership is the free-text devices.room matched by name.
    CREATE TABLE IF NOT EXISTS rooms (
      id          BIGSERIAL PRIMARY KEY,
      owner_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      name        TEXT NOT NULL,
      icon        TEXT NOT NULL DEFAULT '🏠',
      sort        INT NOT NULL DEFAULT 0,
      created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
      UNIQUE (owner_id, name)
    );
    CREATE INDEX IF NOT EXISTS idx_rooms_owner ON rooms(owner_id);

    -- Scenes: one-tap presets that publish a batch of device commands.
    CREATE TABLE IF NOT EXISTS scenes (
      id          BIGSERIAL PRIMARY KEY,
      owner_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      name        TEXT NOT NULL,
      icon        TEXT NOT NULL DEFAULT '✨',
      actions     JSONB NOT NULL DEFAULT '[]'::jsonb,
      favorite    BOOLEAN NOT NULL DEFAULT false,
      created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_scenes_owner ON scenes(owner_id);

    -- Events: the notification center + activity log feed.
    CREATE TABLE IF NOT EXISTS events (
      id          BIGSERIAL PRIMARY KEY,
      owner_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      device_id   TEXT,
      kind        TEXT NOT NULL DEFAULT 'info',   -- info | alert | success | security | activity
      title       TEXT NOT NULL,
      body        TEXT NOT NULL DEFAULT '',
      read        BOOLEAN NOT NULL DEFAULT false,
      ts          TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_events_owner_ts ON events(owner_id, ts DESC);

    -- Admin role flag for the control-plane admin console.
    ALTER TABLE users ADD COLUMN IF NOT EXISTS is_admin BOOLEAN NOT NULL DEFAULT false;

    -- Tier within the admin console: 'observer' (read-only) or 'operator'
    -- (today's full access). Additive and backwards compatible — is_admin is
    -- still the gate for whether a row can reach /admin at all, this only
    -- subdivides what it may do once inside.
    --
    -- The default is load-bearing, not incidental: every account that is
    -- already is_admin gets 'operator' the moment this column exists, which is
    -- byte-identical to the access it had the instant before the migration
    -- ran. A default of 'observer' here would quietly demote every current
    -- admin to read-only on deploy and lock people out of production.
    ALTER TABLE users ADD COLUMN IF NOT EXISTS admin_role TEXT NOT NULL DEFAULT 'operator';

    -- Profile picture, as supplied by the identity provider at SSO sign-in.
    --
    -- Stored as the IdP's URL rather than a copy of the bytes. The directory is
    -- the owner of what a federated person looks like, so re-fetching on every
    -- sign-in keeps this correct when they change their photo upstream, and a
    -- stale copy here can never outlive the account it belongs to.
    ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url TEXT NOT NULL DEFAULT '';

    -- Session revocation.
    --
    -- JWTs are stateless, so until these existed there was no way to end a
    -- session early: a stolen phone kept control of the owner's locks and gates
    -- for the full token lifetime, blocking an account did nothing, and there
    -- was no "sign out everywhere". token_epoch is stamped into every token and
    -- compared on each request, so bumping it invalidates every token that
    -- account has ever been issued.
    --
    -- Default 0 matches the absent claim on tokens issued before this shipped,
    -- so deploying it does not sign the whole user base out.
    ALTER TABLE users ADD COLUMN IF NOT EXISTS token_epoch BIGINT NOT NULL DEFAULT 0;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS blocked BOOLEAN NOT NULL DEFAULT false;

    -- Password reset codes.
    --
    -- Separate from pending_registrations because the two mean different
    -- things: one holds an account that does not exist yet, this one proves
    -- control of an address for an account that does. Sharing the table would
    -- make it possible for a reset to overwrite a sign-up in progress.
    --
    -- Only a bcrypt hash of the code is stored, so a database read does not
    -- hand over the ability to reset anyone's password.
    CREATE TABLE IF NOT EXISTS password_resets (
      email       TEXT PRIMARY KEY,
      otp_hash    TEXT NOT NULL,
      attempts    INT NOT NULL DEFAULT 0,
      expires_at  TIMESTAMPTZ NOT NULL,
      created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    -- Brute-force lockouts.
    --
    -- The rate limiter in front of /auth caps the pace at twenty requests a
    -- minute per address. That is a flood control, not a guessing control:
    -- twelve hundred attempts an hour, indefinitely, is a workable rate for
    -- walking a password list.
    --
    -- Rows are keyed by scope so the same table can hold both halves of the
    -- defence. An address alone lets a botnet try one password per account
    -- from a different IP each time; an account alone lets one address work
    -- through a list of accounts, failing once each, and trip nothing.
    CREATE TABLE IF NOT EXISTS auth_lockouts (
      scope_kind        TEXT NOT NULL CHECK (scope_kind IN ('ip', 'email')),
      scope_value       TEXT NOT NULL,
      failures          INT NOT NULL DEFAULT 0,
      window_started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      blocked_until     TIMESTAMPTZ,
      updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
      PRIMARY KEY (scope_kind, scope_value)
    );

    -- Answering "is this caller locked out" on every sign-in attempt.
    CREATE INDEX IF NOT EXISTS auth_lockouts_blocked_idx
      ON auth_lockouts (blocked_until) WHERE blocked_until IS NOT NULL;

    -- Scheduler tick claims.
    --
    -- Time-triggered automations were de-duplicated by a variable inside the
    -- scheduler closure, which fails in two ways. Across replicas each process
    -- keeps its own copy, so every schedule fires once per replica. And on a
    -- single replica the variable resets when the process restarts, so a deploy
    -- at 07:30 re-runs every 07:30 automation — lights and pumps switching a
    -- second time because we shipped.
    --
    -- The primary key makes claiming a minute atomic: the insert either wins or
    -- conflicts, and only the winner runs the tick.
    CREATE TABLE IF NOT EXISTS scheduler_ticks (
      tick_key    TEXT PRIMARY KEY,
      ran_at      TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_scheduler_ticks_ran_at ON scheduler_ticks(ran_at);

    -- Enrolled faces for the FaceDoor lock.
    --
    -- A profile is a person; the samples are that person's face under
    -- different conditions — glasses on and off, a beard grown since, the
    -- hall light on and off. One sample is a door that stops recognising you
    -- when you shave, which is why enrolment takes several.
    --
    -- Scoped to a device, not to an account: a household with a front door
    -- and a garage door should be able to admit the cleaner to one and not
    -- the other, and a roster shared across every door cannot express that.
    CREATE TABLE IF NOT EXISTS face_profiles (
      id           BIGSERIAL PRIMARY KEY,
      owner_id     BIGINT REFERENCES users(id) ON DELETE CASCADE,
      device_id    TEXT NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
      name         TEXT NOT NULL,
      -- "resident" | "guest" | "staff". Advisory: it labels the event log
      -- and the UI, and grants nothing on its own.
      role         TEXT NOT NULL DEFAULT 'resident',
      enabled      BOOLEAN NOT NULL DEFAULT true,
      -- Local time-of-day window. Both null means always.
      allow_from   TEXT,
      allow_to     TEXT,
      expires_at   TIMESTAMPTZ,
      created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
      UNIQUE (device_id, name)
    );
    CREATE INDEX IF NOT EXISTS idx_face_profiles_device ON face_profiles(device_id);

    -- The embeddings themselves.
    --
    -- A descriptor, never a photograph. A household face database is a
    -- serious liability if it leaks and an embedding cannot be turned back
    -- into a recognisable picture, so an enrolment photo is discarded the
    -- moment its descriptor is computed and never reaches this table.
    CREATE TABLE IF NOT EXISTS face_samples (
      id           BIGSERIAL PRIMARY KEY,
      profile_id   BIGINT NOT NULL REFERENCES face_profiles(id) ON DELETE CASCADE,
      descriptor   JSONB NOT NULL,
      -- "mobile" | "device" | "web": where the face was captured, which is
      -- the first question asked when an enrolment is disputed.
      source       TEXT NOT NULL DEFAULT 'mobile',
      quality      REAL,
      created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_face_samples_profile ON face_samples(profile_id);

    -- Every decision the door made, including the refusals.
    --
    -- Kept separately from telemetry because the refusals are the valuable
    -- part: a stranger tried the door at 03:00 is the event somebody wants
    -- to find, and it is exactly the one a "recent activity" feed built from
    -- successful unlocks would omit.
    CREATE TABLE IF NOT EXISTS face_attempts (
      id           BIGSERIAL PRIMARY KEY,
      device_id    TEXT NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
      profile_id   BIGINT REFERENCES face_profiles(id) ON DELETE SET NULL,
      name         TEXT NOT NULL DEFAULT '',
      outcome      TEXT NOT NULL,
      distance     REAL,
      granted      BOOLEAN NOT NULL DEFAULT false,
      reason       TEXT NOT NULL DEFAULT '',
      at           TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_face_attempts_device_at ON face_attempts(device_id, at DESC);

    -- Household sharing.
    --
    -- A home is an account; its members are other accounts granted access to
    -- it. Before this, sharing a home meant sharing the password, which
    -- grants everything including the ability to lock the owner out and
    -- leaves no record of who actually opened the door.
    --
    -- The owner is deliberately NOT a row here. A home has exactly one, it is
    -- the account itself, and storing it as a membership creates a state
    -- where a home has two owners or none — both of which are worse than the
    -- redundancy this avoids.
    CREATE TABLE IF NOT EXISTS home_members (
      home_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      member_id   BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      role        TEXT NOT NULL DEFAULT 'limited',
      invited_by  BIGINT REFERENCES users(id) ON DELETE SET NULL,
      created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
      PRIMARY KEY (home_id, member_id),
      -- Somebody cannot be a member of their own home; they are its owner,
      -- and a row saying otherwise would give them two different roles.
      CHECK (home_id <> member_id)
    );
    CREATE INDEX IF NOT EXISTS idx_home_members_member ON home_members(member_id);

    -- Invitations.
    --
    -- Single-use and time-boxed. A standing invite code is a password to
    -- somebody's house that they cannot see and did not choose, and the one
    -- thing worse than sharing a password is sharing one that never expires.
    CREATE TABLE IF NOT EXISTS home_invites (
      code        TEXT PRIMARY KEY,
      home_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      role        TEXT NOT NULL DEFAULT 'limited',
      -- Optional: when set, only this address may redeem it.
      email       TEXT NOT NULL DEFAULT '',
      created_by  BIGINT REFERENCES users(id) ON DELETE SET NULL,
      expires_at  TIMESTAMPTZ NOT NULL,
      used_by     BIGINT REFERENCES users(id) ON DELETE SET NULL,
      used_at     TIMESTAMPTZ,
      revoked     BOOLEAN NOT NULL DEFAULT false,
      created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_home_invites_home ON home_invites(home_id);

    -- Which assistants a customer has linked.
    --
    -- Account linking is otherwise stateless — a JWT exchange with nothing
    -- stored — and that is what lets the API scale sideways. This table exists
    -- for the three things that cannot be done without a record: honouring an
    -- unlink, knowing who to push state to, and being able to answer "which
    -- assistants can control my house?".
    --
    -- The Alexa columns hold the grant Amazon issues once during AcceptGrant
    -- and never repeats. Losing it stops proactive updates for that user until
    -- they disable and re-enable the skill, so it is written before the
    -- AcceptGrant response is sent.
    CREATE TABLE IF NOT EXISTS assistant_links (
      user_id             BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      assistant           TEXT NOT NULL,
      linked_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
      last_sync_at        TIMESTAMPTZ,
      alexa_refresh_token TEXT,
      alexa_access_token  TEXT,
      alexa_expires_at    TIMESTAMPTZ,
      PRIMARY KEY (user_id, assistant),
      CHECK (assistant IN ('google', 'alexa'))
    );
    CREATE INDEX IF NOT EXISTS idx_assistant_links_assistant ON assistant_links(assistant);

    -- Refresh tokens, for detecting replay.
    --
    -- token_epoch can revoke a session but cannot tell a thief's use of a token
    -- from the owner's — both present a valid signature. Refresh tokens are
    -- single-use and rotate, so a stolen one being presented twice is a signal
    -- rather than a guess, and the whole family is torn down.
    --
    -- Stored as a SHA-256 hash rather than bcrypt on purpose: lookup is BY the
    -- hash, and bcrypt's per-row salt would force a full-table scan. A fast
    -- hash is safe here because the token is 256 bits of randomness, so there
    -- is no dictionary to attack.
    CREATE TABLE IF NOT EXISTS refresh_tokens (
      id          BIGSERIAL PRIMARY KEY,
      user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      family_id   TEXT NOT NULL,
      token_hash  TEXT NOT NULL UNIQUE,
      used_at     TIMESTAMPTZ,
      expires_at  TIMESTAMPTZ NOT NULL,
      created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_refresh_user ON refresh_tokens(user_id);
    CREATE INDEX IF NOT EXISTS idx_refresh_family ON refresh_tokens(family_id);
    CREATE INDEX IF NOT EXISTS idx_refresh_expires ON refresh_tokens(expires_at);

    -- Email-OTP sign-up: the account is only created after the code is verified.
    CREATE TABLE IF NOT EXISTS pending_registrations (
      email       TEXT PRIMARY KEY,
      name        TEXT NOT NULL DEFAULT '',
      password    TEXT NOT NULL,
      otp_hash    TEXT NOT NULL,
      attempts    INT NOT NULL DEFAULT 0,
      expires_at  TIMESTAMPTZ NOT NULL,
      created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    -- Zone-1 gate guest passes: time-boxed QR/PIN codes that open a barrier.
    CREATE TABLE IF NOT EXISTS gate_passes (
      id          BIGSERIAL PRIMARY KEY,
      owner_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      device_id   TEXT NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
      code        TEXT NOT NULL UNIQUE,
      label       TEXT NOT NULL DEFAULT 'Guest',
      valid_from  TIMESTAMPTZ NOT NULL DEFAULT now(),
      valid_to    TIMESTAMPTZ NOT NULL,
      max_uses    INT NOT NULL DEFAULT 1,
      uses        INT NOT NULL DEFAULT 0,
      revoked     BOOLEAN NOT NULL DEFAULT false,
      last_used   TIMESTAMPTZ,
      created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_gate_passes_owner ON gate_passes(owner_id, created_at DESC);
    CREATE INDEX IF NOT EXISTS idx_gate_passes_code ON gate_passes(code);

    /*
     * A vehicle tag, and when it is allowed through.
     *
     * The device holds a bare list of numbers in NVS so the barrier keeps
     * working with no network. Everything that makes that list *mean*
     * something — whose car it is, until when, on which days — lives here, and
     * the platform re-pushes the list as those rules come in and out of force.
     *
     * Splitting it that way is deliberate. The gate has no clock it can trust
     * and no way to be told the time when the network is down, so a rule it
     * cannot evaluate is a rule it would silently ignore; better that the list
     * it holds is simply the set of tags that may pass right now.
     */
    CREATE TABLE IF NOT EXISTS gate_tags (
      id          BIGSERIAL PRIMARY KEY,
      device_id   TEXT NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
      owner_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      -- The number the reader reports, after parity and format decoding.
      tag         BIGINT NOT NULL,
      label       TEXT NOT NULL DEFAULT '',
      vehicle     TEXT NOT NULL DEFAULT '',
      active      BOOLEAN NOT NULL DEFAULT true,
      valid_from  TIMESTAMPTZ,
      valid_to    TIMESTAMPTZ,
      /*
       * Days of the week, 0 = Sunday. Empty means every day.
       *
       * A contractor allowed on site Monday to Friday is the ordinary case,
       * and writing it as a rule rather than relying on somebody remembering
       * to revoke and reissue is the difference between a restriction that
       * stays true and one that quietly stops being enforced.
       */
      days        SMALLINT[] NOT NULL DEFAULT '{}',
      -- Minutes from local midnight. Null/null means any time. A window whose
      -- end is before its start spans midnight, which is a night shift.
      from_minute INT,
      to_minute   INT,
      note        TEXT NOT NULL DEFAULT '',
      created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_gate_tags_device ON gate_tags(device_id, active);
    /* One row per physical tag per gate — re-enrolling updates rather than
       duplicating, so a replacement cannot leave the old rule in force. */
    CREATE UNIQUE INDEX IF NOT EXISTS uq_gate_tags_device_tag ON gate_tags(device_id, tag);

    /*
     * Every scan, allowed or not.
     *
     * This is the part a gate is actually for. Without it the device publishes
     * a telemetry row nobody reads and the question "who came in last night"
     * has no answer at all — which is the question that gets asked, and the
     * only reason anybody fits a reader rather than a keypad.
     *
     * Denials are recorded as carefully as admissions: a tag refused at 3am is
     * more interesting than one accepted at 9.
     */
    CREATE TABLE IF NOT EXISTS gate_events (
      id          BIGSERIAL PRIMARY KEY,
      device_id   TEXT NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
      owner_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      tag         BIGINT,
      tag_id      BIGINT REFERENCES gate_tags(id) ON DELETE SET NULL,
      label       TEXT NOT NULL DEFAULT '',
      allowed     BOOLEAN NOT NULL,
      -- allowed | unknown-tag | revoked | not-yet-valid | expired |
      -- wrong-day | wrong-time | pass | manual
      reason      TEXT NOT NULL DEFAULT 'allowed',
      at          TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_gate_events_device ON gate_events(device_id, at DESC);
    CREATE INDEX IF NOT EXISTS idx_gate_events_owner ON gate_events(owner_id, at DESC);

    -- Developer API keys.
    --
    -- Long-lived, independently revocable, scoped credentials for third-party
    -- integrations. See api-keys.ts for why these exist rather than handing a
    -- developer a login JWT, and why the secret is SHA-256 and not bcrypt.
    --
    -- token_hash is UNIQUE so authentication is a single index probe.
    CREATE TABLE IF NOT EXISTS api_keys (
      id              BIGSERIAL PRIMARY KEY,
      owner_id        BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      name            TEXT NOT NULL DEFAULT '',
      env             TEXT NOT NULL DEFAULT 'live',
      token_hash      TEXT NOT NULL UNIQUE,
      prefix          TEXT NOT NULL,
      scopes          TEXT[] NOT NULL DEFAULT '{}',
      -- Empty means server-to-server only: a request carrying any Origin
      -- header is refused. See originAllowed() for what this does and does
      -- not guarantee.
      allowed_origins TEXT[] NOT NULL DEFAULT '{}',
      expires_at      TIMESTAMPTZ,
      revoked_at      TIMESTAMPTZ,
      last_used_at    TIMESTAMPTZ,
      request_count   BIGINT NOT NULL DEFAULT 0,
      created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_api_keys_owner ON api_keys(owner_id, created_at DESC);

    -- Outbound webhooks.
    --
    -- Without these the only way for a developer's backend to learn that a
    -- sensor tripped is to poll, which is both slower than the event and more
    -- load than delivering it once. Deliveries are HMAC-signed so the receiver
    -- can prove the request came from us; see webhooks.ts.
    --
    -- The secret is stored in plaintext on purpose and unusually: unlike an API
    -- key, we are the party that must COMPUTE the HMAC on every delivery, so a
    -- one-way hash would make it useless. It is a signing key, not a
    -- credential that authenticates anyone to us.
    CREATE TABLE IF NOT EXISTS webhooks (
      id            BIGSERIAL PRIMARY KEY,
      owner_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      url           TEXT NOT NULL,
      secret        TEXT NOT NULL,
      events        TEXT[] NOT NULL DEFAULT '{}',
      -- Empty means every device the account owns.
      device_ids    TEXT[] NOT NULL DEFAULT '{}',
      enabled       BOOLEAN NOT NULL DEFAULT true,
      failures      INT NOT NULL DEFAULT 0,
      last_status   INT,
      last_error    TEXT NOT NULL DEFAULT '',
      last_at       TIMESTAMPTZ,
      created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_webhooks_owner ON webhooks(owner_id);
    CREATE INDEX IF NOT EXISTS idx_webhooks_enabled ON webhooks(enabled) WHERE enabled;

    -- Device registry.
    --
    -- serial is the customer-facing identifier printed on the unit. devices.id
    -- is derived from the chip id and is fine as a key but poor on a label —
    -- see serial.ts. NULL is allowed because rows created before this existed
    -- have no serial until they are backfilled; the partial UNIQUE index means
    -- those NULLs do not collide with each other.
    ALTER TABLE devices ADD COLUMN IF NOT EXISTS serial TEXT;
    CREATE UNIQUE INDEX IF NOT EXISTS idx_devices_serial ON devices(serial) WHERE serial IS NOT NULL;

    -- The hardware id the device reported at provisioning. Kept so a unit that
    -- is factory reset can be recognised as the same physical board, and so a
    -- serial can be regenerated identically rather than a second one issued
    -- while the label on the case still shows the first.
    ALTER TABLE devices ADD COLUMN IF NOT EXISTS hwid TEXT NOT NULL DEFAULT '';

    -- Credential lifecycle.
    --
    -- The claim key is bcrypt-hashed, so it cannot be read back — not by an
    -- admin, not by us. These columns are what can honestly be shown instead:
    -- when the credential was issued, when it was last replaced, and how often.
    -- Support answering "what is my device key" has to reissue, and reissuing
    -- needs to be visible.
    ALTER TABLE devices ADD COLUMN IF NOT EXISTS key_issued_at TIMESTAMPTZ NOT NULL DEFAULT now();
    ALTER TABLE devices ADD COLUMN IF NOT EXISTS key_rotated_at TIMESTAMPTZ;
    ALTER TABLE devices ADD COLUMN IF NOT EXISTS key_rotations INT NOT NULL DEFAULT 0;

    -- Notes the internal team keeps against a unit (RMA, batch, customer case).
    ALTER TABLE devices ADD COLUMN IF NOT EXISTS notes TEXT NOT NULL DEFAULT '';
    ALTER TABLE devices ADD COLUMN IF NOT EXISTS batch TEXT NOT NULL DEFAULT '';

    -- Administrative audit trail for devices.
    --
    -- The activity feed in the events table belongs to the customer and
    -- answers "what did my house do". This answers a different question —
    -- "who inside the company changed this unit's ownership or reissued its
    -- credential, and why" — and it must not be mixed into a feed the
    -- customer can clear.
    --
    -- actor_id is nullable and ON DELETE SET NULL: an audit entry has to
    -- survive the departure of the operator who made it, which is precisely
    -- when it is most likely to be read.
    CREATE TABLE IF NOT EXISTS device_audit (
      id          BIGSERIAL PRIMARY KEY,
      device_id   TEXT NOT NULL,
      actor_id    BIGINT REFERENCES users(id) ON DELETE SET NULL,
      actor_email TEXT NOT NULL DEFAULT '',
      action      TEXT NOT NULL,
      detail      JSONB NOT NULL DEFAULT '{}'::jsonb,
      note        TEXT NOT NULL DEFAULT '',
      ts          TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_device_audit_device ON device_audit(device_id, ts DESC);
    CREATE INDEX IF NOT EXISTS idx_device_audit_actor ON device_audit(actor_id, ts DESC);

    /*
     * ANPR plate reads.
     *
     * A separate table rather than rows in "telemetry", for three reasons that
     * telemetry cannot satisfy:
     *
     *  - it is queried by plate, not by device and time. "Has KA01AB1234 been
     *    here before" against a JSONB column on the fleet-wide telemetry table
     *    is a sequential scan; here it is an index.
     *  - it holds an image. Telemetry rows are small and are read in bulk for
     *    charts, and a base64 thumbnail on every row would make the energy
     *    dashboard drag megabytes it never looks at.
     *  - it has its own retention. Plate reads are personal data about people
     *    who never agreed to anything, so they expire on a schedule of their
     *    own (ANPR_RETENTION_DAYS) rather than living as long as a power
     *    reading.
     *
     * "plate" is the normalised form (no spaces, corrected) because that is
     * what is compared; "plate_raw" keeps what the recogniser actually said so
     * a disputed read can be investigated rather than argued about.
     */
    CREATE TABLE IF NOT EXISTS plate_reads (
      id           BIGSERIAL PRIMARY KEY,
      device_id    TEXT NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
      owner_id     BIGINT REFERENCES users(id) ON DELETE CASCADE,
      capture_id   BIGINT NOT NULL DEFAULT 0,
      plate        TEXT NOT NULL DEFAULT '',
      plate_raw    TEXT NOT NULL DEFAULT '',
      confidence   INT NOT NULL DEFAULT 0,
      votes        INT NOT NULL DEFAULT 0,
      samples      INT NOT NULL DEFAULT 0,
      kind         TEXT NOT NULL DEFAULT 'unknown',
      -- recognised | unrecognised
      status       TEXT NOT NULL DEFAULT 'unrecognised',
      -- why an unrecognised read failed: no_recogniser | no_plate | timeout |
      -- provider_error | invalid_format
      reason       TEXT NOT NULL DEFAULT '',
      -- allow | deny | watch | unknown — what the rules said at the time.
      -- Stored rather than recomputed: a rule edited next week must not
      -- silently rewrite what the gate did last night.
      decision     TEXT NOT NULL DEFAULT 'unknown',
      rule_id      BIGINT,
      trigger      TEXT NOT NULL DEFAULT 'motion',
      -- Base64 JPEG of the frame the plate was read from. Nullable because a
      -- deployment may turn images off entirely, and because the retention
      -- sweep clears it before deleting the row.
      thumb        TEXT,
      ms           INT NOT NULL DEFAULT 0,
      ts           TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_plate_reads_device_ts ON plate_reads(device_id, ts DESC);
    CREATE INDEX IF NOT EXISTS idx_plate_reads_owner_ts ON plate_reads(owner_id, ts DESC);
    -- The "have I seen this vehicle" lookup, and the retention sweep.
    CREATE INDEX IF NOT EXISTS idx_plate_reads_plate ON plate_reads(owner_id, plate, ts DESC) WHERE plate <> '';
    CREATE INDEX IF NOT EXISTS idx_plate_reads_ts ON plate_reads(ts);

    /*
     * The allow / deny / watch list.
     *
     * "plate" is stored normalised, by the same function that normalises a
     * read (normalisePlate in anpr/plate.ts), so "KA 01 AB 1234" typed by a
     * person and "KA01AB1234" read by a camera are the same row. Doing this
     * anywhere other than at both ends is how an allow-list silently stops
     * matching.
     *
     * A rule may be scoped to one device or left global for the account: a
     * household wants one list across the front and back gates, while a
     * business with two sites does not.
     */
    CREATE TABLE IF NOT EXISTS plate_rules (
      id          BIGSERIAL PRIMARY KEY,
      owner_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      plate       TEXT NOT NULL,
      -- allow | deny | watch
      kind        TEXT NOT NULL DEFAULT 'allow',
      label       TEXT NOT NULL DEFAULT '',
      -- NULL means every ANPR camera on the account.
      device_id   TEXT REFERENCES devices(id) ON DELETE CASCADE,
      -- Optional validity window, for a contractor or a visitor.
      valid_from  TIMESTAMPTZ,
      valid_to    TIMESTAMPTZ,
      enabled     BOOLEAN NOT NULL DEFAULT true,
      hits        BIGINT NOT NULL DEFAULT 0,
      last_hit_at TIMESTAMPTZ,
      created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_plate_rules_owner ON plate_rules(owner_id, plate);
    -- One rule per plate per scope. A plate that is both allowed and denied is
    -- not a policy, it is a bug waiting to be argued about at a barrier, so the
    -- database refuses to hold that state at all.
    CREATE UNIQUE INDEX IF NOT EXISTS idx_plate_rules_unique
      ON plate_rules(owner_id, plate, COALESCE(device_id, ''));

    /*
     * Visits — one vehicle's stay, pairing an entry read with an exit read.
     *
     * Derived rather than raw, and stored rather than recomputed, for one
     * reason: the question "how long was that van inside" cannot be answered
     * by looking at a read. It needs two reads matched across time, and
     * matching them on every page load means re-pairing months of history for
     * every plate on every request.
     *
     * THE UNPAIRED STATES ARE FIRST-CLASS, NOT ERRORS
     *
     * A gate camera misses reads. A car tailgates another through one barrier
     * cycle, a plate is obscured by rain, a van leaves while the device is
     * rebooting. If the model only allowed clean entry/exit pairs, the first
     * missed read would corrupt every subsequent pairing for that vehicle —
     * every later entry would close a visit that never ended, and dwell times
     * would be nonsense from then on. So a visit may legitimately have no
     * entry or no exit, it says which, and pairing resumes correctly at the
     * next clean read.
     *
     *   open          inside now: entry seen, no exit yet
     *   closed        entry and exit both read
     *   entry_missed  seen leaving with no recorded arrival
     *   exit_missed   arrived again before the previous departure was read
     */
    CREATE TABLE IF NOT EXISTS plate_visits (
      id             BIGSERIAL PRIMARY KEY,
      owner_id       BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      plate          TEXT NOT NULL,
      entry_at       TIMESTAMPTZ,
      exit_at        TIMESTAMPTZ,
      entry_read_id  BIGINT,
      exit_read_id   BIGINT,
      entry_device   TEXT,
      exit_device    TEXT,
      status         TEXT NOT NULL DEFAULT 'open',
      created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_plate_visits_owner_plate
      ON plate_visits(owner_id, plate, COALESCE(entry_at, exit_at) DESC);
    -- "Who is inside right now" is the query a gate operator runs most, and it
    -- must not scan closed history to answer it.
    CREATE INDEX IF NOT EXISTS idx_plate_visits_open
      ON plate_visits(owner_id, plate) WHERE status = 'open';
    CREATE INDEX IF NOT EXISTS idx_plate_visits_created ON plate_visits(created_at);

    /*
     * Direction of travel for the read, resolved by the control plane from the
     * camera's lane setting. Nullable because reads predating this column, and
     * reads from a lane whose direction could not be resolved, genuinely have
     * no answer — and "unknown" must not be silently rendered as "in".
     */
    ALTER TABLE plate_reads ADD COLUMN IF NOT EXISTS direction TEXT;
    ALTER TABLE plate_reads ADD COLUMN IF NOT EXISTS visit_id BIGINT;

    /*
     * Per-account ANPR policy.
     *
     * One row per owner rather than per device: a site with an entry camera
     * and an exit camera has one capacity and one overstay rule between them,
     * and hanging those off a device would mean the answer changed depending
     * on which lane a vehicle happened to use.
     *
     * Every limit is nullable and every limit off by default. A capacity of 0
     * would mean "full", and a customer who never asked for capacity
     * management must not discover it by having their gate start refusing
     * cars.
     */
    CREATE TABLE IF NOT EXISTS anpr_settings (
      owner_id        BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
      -- Vehicles the site holds. NULL = unlimited.
      capacity        INT,
      -- Hours after which a vehicle still inside is flagged. NULL = never.
      overstay_hours  INT,
      -- Notify the first time a plate is ever seen on this account.
      alert_unknown   BOOLEAN NOT NULL DEFAULT false,
      -- Notify when occupancy reaches capacity.
      alert_full      BOOLEAN NOT NULL DEFAULT true,
      /*
       * Daily report.
       *
       * The address is stored per account rather than taken from the login
       * email, because the person who should read a gate report is often not
       * the person who owns the account — a facilities inbox, a security desk,
       * a building manager. Defaulting to the account holder and offering no
       * way to change it would make the feature useless to exactly the sites
       * that need it most.
       *
       * NULL means no report. "report_hour" is IST, matching the automation
       * scheduler, so a report and a schedule set for the same hour mean the
       * same hour.
       */
      report_email    TEXT,
      report_hour     INT NOT NULL DEFAULT 7,
      updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    /*
     * Overstay is announced once per visit, not once per sweep.
     *
     * A alert that repeats every ten minutes for a van that is legitimately
     * parked gets muted within the hour, and a muted channel is where the
     * next real alert goes to die. This is the same reasoning that makes the
     * Sentinel's gas alarm latch rather than re-fire, and its mute expire.
     */
    ALTER TABLE plate_visits ADD COLUMN IF NOT EXISTS overstay_alerted_at TIMESTAMPTZ;

    -- Added after anpr_settings shipped, so existing rows need them too.
    ALTER TABLE anpr_settings ADD COLUMN IF NOT EXISTS report_email TEXT;
    ALTER TABLE anpr_settings ADD COLUMN IF NOT EXISTS report_hour INT NOT NULL DEFAULT 7;

    /*
     * The capture, when it lives in a bucket rather than in this column.
     *
     * "thumb" is kept and still read: rows written before object storage was
     * configured hold their image there, and a deployment with no bucket still
     * writes there. The two are mutually exclusive per row, and the read path
     * prefers the key — see GET /anpr/reads/:id/image.
     *
     * "image_bytes" is the size of the object. It is stored rather than
     * derived because the only other way to answer "how much is this account
     * holding" is to HEAD every object, and the retention sweep needs to
     * report what it freed after the objects are already gone.
     */
    ALTER TABLE plate_reads ADD COLUMN IF NOT EXISTS image_key TEXT;
    ALTER TABLE plate_reads ADD COLUMN IF NOT EXISTS image_bytes INT NOT NULL DEFAULT 0;
    /*
     * The retention sweep's working set: rows that still name an object older
     * than the image window. Partial, because the overwhelming majority of
     * rows have no key at all and scanning them to find the few that do is the
     * one query that gets slower every day the product succeeds.
     */
    CREATE INDEX IF NOT EXISTS idx_plate_reads_image_key
      ON plate_reads(ts) WHERE image_key IS NOT NULL;

    /*
     * ANPR on a camera that is not an ANPR camera.
     *
     * The anpr-cam firmware decides when a vehicle is worth photographing and
     * publishes a burst on cv/<id>/anpr. An ordinary "camera" cannot: it
     * detects motion and it takes snapshots, but it has no notion of a lane, a
     * burst or a capture id.
     *
     * That gap is the difference between "ANPR works if you buy the ANPR
     * camera" and "ANPR works on the camera you already have on the gate". The
     * ordinary camera already publishes a {type:"motion"} telemetry event and
     * already answers {"action":"snapshot"} — so the missing piece is a lane
     * definition and something to drive the burst, and both can live here. No
     * firmware change, and a device already deployed and online can start
     * reading plates.
     *
     * One row per camera. "direction" mirrors the anpr-cam state key of the
     * same name and means the same thing, so visits.ts needs no knowledge of
     * which kind of camera produced a read.
     */
    CREATE TABLE IF NOT EXISTS anpr_lanes (
      device_id     TEXT PRIMARY KEY REFERENCES devices(id) ON DELETE CASCADE,
      owner_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      enabled       BOOLEAN NOT NULL DEFAULT true,
      -- in | out | both — the mounting decides this, exactly as on anpr-cam.
      direction     TEXT NOT NULL DEFAULT 'both',
      -- Frames per trigger. Three is the anpr-cam default and the number
      -- voteOnBurst is tuned for: two give agreement, three break a tie.
      burst         INT NOT NULL DEFAULT 3,
      -- Milliseconds between snapshot requests within one burst.
      burst_gap_ms  INT NOT NULL DEFAULT 400,
      /*
       * Minimum gap between triggers, in milliseconds.
       *
       * The camera's own motion detector re-arms after MOTION_COOLDOWN_MS
       * (15 s), but a lane cooldown is a separate lever: it is what stops one
       * vehicle sitting in frame with its indicator flashing from being read
       * as twelve arrivals, and it is what bounds the cost of a recogniser
       * that is billed per call.
       */
      cooldown_ms   INT NOT NULL DEFAULT 8000,
      /*
       * Turn the illuminator on for the burst and off again afterwards.
       *
       * Off by default. A camera indoors does not want it, and a flash LED
       * held on continuously is both a nuisance and the fastest way to cook an
       * ESP32-CAM — which is why it is pulsed for the burst rather than left
       * to a user to remember to turn off.
       */
      illuminate    INT NOT NULL DEFAULT 0,
      triggers      BIGINT NOT NULL DEFAULT 0,
      last_trigger_at TIMESTAMPTZ,
      created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_anpr_lanes_owner ON anpr_lanes(owner_id);

    /*
     * A camera pressed into service as the eyes of a door lock.
     *
     * FaceDoor's design assumes "the hub's AI node" watches a camera and posts
     * descriptors to /face/match. No such node exists in a Circuvent home, so
     * the feature was complete on paper and inert in practice: profiles could
     * be created, samples stored and thresholds tuned, and nothing ever looked
     * at anybody. This table is what closes that gap, using the plain ESP32
     * camera a customer already owns.
     *
     * It is deliberately the same arrangement as anpr_lanes rather than a
     * clever generalisation of it. The two share a mechanism — trigger, ask
     * for a burst of snapshots, feed the frames somewhere — but they differ in
     * every decision that matters: what triggers them, how long the answer may
     * take, and what happens when they are unsure. Merging them would mean one
     * set of tuning constants serving a car park barrier and a front door.
     *
     * lock_id is nullable on purpose. A camera can be enrolling and
     * recognising faces before any lock is fitted — useful on its own, and it
     * lets somebody set the roster up before the hardware arrives.
     */
    CREATE TABLE IF NOT EXISTS face_doors (
      device_id     TEXT PRIMARY KEY REFERENCES devices(id) ON DELETE CASCADE,
      owner_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      lock_id       TEXT REFERENCES devices(id) ON DELETE SET NULL,
      enabled       BOOLEAN NOT NULL DEFAULT true,
      /*
       * Frames per trigger. Three, because a face is a moving target: one
       * frame catches a blink or a turn, and the extra two cost a few hundred
       * milliseconds. Unlike ANPR these are not voted on — the first frame
       * that yields a confident match wins, because the person is waiting.
       */
      burst         INT NOT NULL DEFAULT 3,
      burst_gap_ms  INT NOT NULL DEFAULT 450,
      /*
       * Minimum gap between motion triggers.
       *
       * Shorter than a lane's, because the cost of missing a person is that
       * they stand at their own front door wondering why it will not open,
       * whereas a missed number plate is read again on the next pass.
       */
      cooldown_ms   INT NOT NULL DEFAULT 4000,
      -- Pulse the illuminator for the burst. A door is used after dark far
      -- more often than a driveway camera is.
      illuminate    INT NOT NULL DEFAULT 0,
      triggers      BIGINT NOT NULL DEFAULT 0,
      last_trigger_at TIMESTAMPTZ,
      created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_face_doors_owner ON face_doors(owner_id);
    CREATE INDEX IF NOT EXISTS idx_face_doors_lock ON face_doors(lock_id);

    /*
     * ========================= ATTENDANCE ================================
     *
     * RFID attendance and access control: a school gate, an office entrance,
     * a server-room door.
     *
     * WHY THIS IS NOT BUILT ON gate_passes OR plate_rules
     *
     * Both of those answer "may this thing through, right now" and then forget
     * about it. An attendance system's whole product is the opposite: the
     * durable, per-person, per-day record that somebody signs, argues about,
     * pays wages from, and is legally required to keep. Access is a side
     * effect of it here, not the point of it.
     *
     * THE ONE MODEL THAT SERVES SCHOOLS AND OFFICES
     *
     * A school has students in classes with guardians and a register. An
     * office has employees in departments with managers and a timesheet. They
     * are the same shape — a person, in a group, expected at certain times,
     * carrying a credential, passing a door — and the differences are wording
     * and which report gets printed. Two parallel schemas would have meant two
     * of everything below and one of them permanently behind the other.
     */

    /*
     * A site: one school, one office, one building.
     *
     * The tuning lives here rather than in a settings table because there is
     * exactly one row per site and a join to fetch six integers is a join
     * nobody enjoys. It is also the level at which these are actually decided
     * — "we allow ten minutes" is a school policy, not a per-door one.
     */
    CREATE TABLE IF NOT EXISTS attend_sites (
      id            BIGSERIAL PRIMARY KEY,
      owner_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      name          TEXT NOT NULL,
      -- school | office | facility. Changes wording and which reports are
      -- offered; never changes what is recorded.
      kind          TEXT NOT NULL DEFAULT 'school',
      /*
       * An IANA zone, not an offset.
       *
       * Attendance is entirely a question of local wall-clock time: "late"
       * means after 08:45 where the building is. An offset would be right for
       * half the year in most of the world and silently wrong for the other
       * half, and the day it broke would be a Monday morning in spring with
       * every arrival marked late.
       */
      timezone      TEXT NOT NULL DEFAULT 'Asia/Kolkata',
      -- Minutes after the start of a window that still count as on time.
      grace_minutes INT NOT NULL DEFAULT 10,
      -- Arriving later than this is not lateness, it is a half day.
      half_day_after_minutes INT NOT NULL DEFAULT 180,
      -- Somebody who never scanned in is marked absent once the day is this
      -- far along. Not at midnight: a register is wanted during the day.
      absent_after_minutes INT NOT NULL DEFAULT 120,
      /*
       * People forget to scan out far more often than they forget to scan in,
       * because leaving is not gated by a door they need opened. Rather than
       * leaving a shift open forever, an unclosed day is closed at the end of
       * its window and flagged, so a timesheet is never quietly wrong.
       */
      auto_out      BOOLEAN NOT NULL DEFAULT true,
      -- Two scans of one card closer together than this are one event, on top
      -- of whatever the terminal already suppressed locally.
      dedupe_seconds INT NOT NULL DEFAULT 60,
      notify_guardians BOOLEAN NOT NULL DEFAULT false,
      notify_absence   BOOLEAN NOT NULL DEFAULT false,
      created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_attend_sites_owner ON attend_sites(owner_id);

    /*
     * When people are expected.
     *
     * windows is one entry per weekday, 0 = Sunday:
     *   {"1":[{"in":"08:30","out":"15:30"}], "6":[], ...}
     * A day with no entry is a non-working day for whoever follows this
     * schedule, which is how a four-day week, a Saturday school and a night
     * shift are all the same feature rather than three.
     */
    CREATE TABLE IF NOT EXISTS attend_schedules (
      id            BIGSERIAL PRIMARY KEY,
      site_id       BIGINT NOT NULL REFERENCES attend_sites(id) ON DELETE CASCADE,
      name          TEXT NOT NULL,
      -- fixed: measured against the window. flexible: measured in hours worked,
      -- so an office with core hours and a factory shift both fit.
      kind          TEXT NOT NULL DEFAULT 'fixed',
      windows       JSONB NOT NULL DEFAULT '{}'::jsonb,
      -- Overrides the site default when set. NULL means "use the site's".
      grace_minutes INT,
      -- For flexible schedules: the hours that make a full day.
      min_minutes   INT NOT NULL DEFAULT 0,
      created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_attend_schedules_site ON attend_schedules(site_id);

    /*
     * A class, a department, a team, a year group.
     *
     * parent_id makes "Grade 5" contain "5A" and "5B" without a second table.
     * A report asked for at any level then walks down, which is what a head of
     * year and a head of department both actually want.
     */
    CREATE TABLE IF NOT EXISTS attend_groups (
      id            BIGSERIAL PRIMARY KEY,
      site_id       BIGINT NOT NULL REFERENCES attend_sites(id) ON DELETE CASCADE,
      parent_id     BIGINT REFERENCES attend_groups(id) ON DELETE SET NULL,
      name          TEXT NOT NULL,
      kind          TEXT NOT NULL DEFAULT 'class',
      schedule_id   BIGINT REFERENCES attend_schedules(id) ON DELETE SET NULL,
      -- Free text: form tutor, line manager, shift supervisor.
      lead_name     TEXT NOT NULL DEFAULT '',
      lead_email    TEXT NOT NULL DEFAULT '',
      created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_attend_groups_site ON attend_groups(site_id);
    CREATE UNIQUE INDEX IF NOT EXISTS idx_attend_groups_name ON attend_groups(site_id, lower(name));

    /*
     * A person on the roll.
     *
     * code is the roll number or employee id — the thing already printed on
     * their badge and typed into the school's other system. Unique per site so
     * an import can find its own rows again, which is what makes a re-import
     * an update rather than a duplicate intake.
     *
     * valid_from / valid_to are what make a leaver stop opening doors on the
     * right day without anybody having to remember. A row is never deleted for
     * that purpose: their attendance history is the part that has to survive.
     */
    CREATE TABLE IF NOT EXISTS attend_people (
      id            BIGSERIAL PRIMARY KEY,
      site_id       BIGINT NOT NULL REFERENCES attend_sites(id) ON DELETE CASCADE,
      group_id      BIGINT REFERENCES attend_groups(id) ON DELETE SET NULL,
      code          TEXT NOT NULL,
      name          TEXT NOT NULL,
      -- student | staff | employee | visitor | contractor
      role          TEXT NOT NULL DEFAULT 'student',
      email         TEXT NOT NULL DEFAULT '',
      phone         TEXT NOT NULL DEFAULT '',
      guardian_name  TEXT NOT NULL DEFAULT '',
      guardian_email TEXT NOT NULL DEFAULT '',
      guardian_phone TEXT NOT NULL DEFAULT '',
      -- Overrides the group's schedule. A part-timer in a full-time team.
      schedule_id   BIGINT REFERENCES attend_schedules(id) ON DELETE SET NULL,
      active        BOOLEAN NOT NULL DEFAULT true,
      valid_from    DATE,
      valid_to      DATE,
      photo_url     TEXT NOT NULL DEFAULT '',
      notes         TEXT NOT NULL DEFAULT '',
      created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE UNIQUE INDEX IF NOT EXISTS idx_attend_people_code ON attend_people(site_id, lower(code));
    CREATE INDEX IF NOT EXISTS idx_attend_people_group ON attend_people(group_id);
    CREATE INDEX IF NOT EXISTS idx_attend_people_site ON attend_people(site_id, active);

    /*
     * A card, fob, PIN or plate belonging to a person.
     *
     * Several per person on purpose: a card and a backup fob, or a card that
     * was lost and replaced. Revoking is a timestamp rather than a delete
     * because "who did this card belong to in March" is a question an incident
     * asks, and a deleted row answers it with silence.
     *
     * The unique index covers only live credentials, so a card number can be
     * reissued to somebody else after the first holder's is revoked — which is
     * what happens to every plastic card eventually — while two people can
     * never hold the same live card at once.
     */
    CREATE TABLE IF NOT EXISTS attend_credentials (
      id            BIGSERIAL PRIMARY KEY,
      site_id       BIGINT NOT NULL REFERENCES attend_sites(id) ON DELETE CASCADE,
      person_id     BIGINT NOT NULL REFERENCES attend_people(id) ON DELETE CASCADE,
      -- card | fob | wiegand | pin | plate
      kind          TEXT NOT NULL DEFAULT 'card',
      -- The number the reader reports. BIGINT because Wiegand 34-bit and
      -- 4-byte MIFARE UIDs both overflow a signed 32-bit column.
      card_number   BIGINT NOT NULL,
      label         TEXT NOT NULL DEFAULT '',
      active        BOOLEAN NOT NULL DEFAULT true,
      issued_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
      revoked_at    TIMESTAMPTZ,
      revoked_reason TEXT NOT NULL DEFAULT '',
      last_seen_at  TIMESTAMPTZ,
      created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE UNIQUE INDEX IF NOT EXISTS idx_attend_cred_live
      ON attend_credentials(site_id, card_number) WHERE active;
    CREATE INDEX IF NOT EXISTS idx_attend_cred_person ON attend_credentials(person_id);
    CREATE INDEX IF NOT EXISTS idx_attend_cred_number ON attend_credentials(site_id, card_number);

    /* A door, gate, turnstile or room that a terminal controls. */
    CREATE TABLE IF NOT EXISTS attend_zones (
      id            BIGSERIAL PRIMARY KEY,
      site_id       BIGINT NOT NULL REFERENCES attend_sites(id) ON DELETE CASCADE,
      name          TEXT NOT NULL,
      -- gate | door | room | turnstile
      kind          TEXT NOT NULL DEFAULT 'door',
      /*
       * Whether passing this zone is a register entry or merely a door being
       * opened. A server-room door should not mark anybody present for the
       * day; the front gate should.
       */
      counts_for_attendance BOOLEAN NOT NULL DEFAULT true,
      created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_attend_zones_site ON attend_zones(site_id);

    /*
     * A reader on a wall.
     *
     * device_id is the primary key because a physical terminal is one device
     * and one place. acl_version is how "the roster changed" is distinguished
     * from "this terminal has the roster": the server bumps it on every roster
     * change and the device reports back what it actually holds, so a terminal
     * that missed a push is visible rather than merely wrong.
     */
    CREATE TABLE IF NOT EXISTS attend_terminals (
      device_id     TEXT PRIMARY KEY REFERENCES devices(id) ON DELETE CASCADE,
      site_id       BIGINT NOT NULL REFERENCES attend_sites(id) ON DELETE CASCADE,
      zone_id       BIGINT REFERENCES attend_zones(id) ON DELETE SET NULL,
      owner_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      name          TEXT NOT NULL DEFAULT 'Entrance',
      -- attendance | access | both. Mirrors the firmware setting.
      mode          TEXT NOT NULL DEFAULT 'both',
      -- in | out | auto
      direction     TEXT NOT NULL DEFAULT 'in',
      enabled       BOOLEAN NOT NULL DEFAULT true,
      acl_version   BIGINT NOT NULL DEFAULT 0,
      acl_pushed_at TIMESTAMPTZ,
      acl_count     INT NOT NULL DEFAULT 0,
      last_punch_at TIMESTAMPTZ,
      created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_attend_terminals_site ON attend_terminals(site_id);

    /*
     * Who may pass which door, and when.
     *
     * A rule with no group and no person applies to everybody; one with a
     * schedule applies only inside it. Deny beats allow at equal priority,
     * because the safe reading of a contradictory rule set is the restrictive
     * one and somebody will eventually write a contradictory rule set.
     */
    CREATE TABLE IF NOT EXISTS attend_rules (
      id            BIGSERIAL PRIMARY KEY,
      site_id       BIGINT NOT NULL REFERENCES attend_sites(id) ON DELETE CASCADE,
      zone_id       BIGINT REFERENCES attend_zones(id) ON DELETE CASCADE,
      group_id      BIGINT REFERENCES attend_groups(id) ON DELETE CASCADE,
      person_id     BIGINT REFERENCES attend_people(id) ON DELETE CASCADE,
      schedule_id   BIGINT REFERENCES attend_schedules(id) ON DELETE SET NULL,
      allow         BOOLEAN NOT NULL DEFAULT true,
      priority      INT NOT NULL DEFAULT 0,
      valid_from    DATE,
      valid_to      DATE,
      note          TEXT NOT NULL DEFAULT '',
      created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_attend_rules_site ON attend_rules(site_id, zone_id);

    /*
     * Every presentation of a card, granted or not.
     *
     * dedupe_key is what makes the terminal's offline replay safe to repeat.
     * A terminal that reconnects mid-drain, or is power-cycled with a queue on
     * it, will send the same punch twice; without an idempotency key the
     * register would show people arriving twice on the morning after an
     * outage, which is precisely the morning it is being scrutinised.
     *
     * It is a composite of device, sequence, card and device clock rather than
     * device and sequence alone: a factory reset restarts the sequence at
     * zero, and a bare (device, seq) key would then silently discard the first
     * few hundred punches of the terminal's new life.
     *
     * person_id is nullable and stays null for a card nobody recognises. That
     * row is the most important one in the table — an unknown card at a school
     * gate at 02:00 is the event somebody goes looking for — so it is stored,
     * not dropped for failing to resolve.
     */
    CREATE TABLE IF NOT EXISTS attend_punches (
      id            BIGSERIAL PRIMARY KEY,
      site_id       BIGINT NOT NULL REFERENCES attend_sites(id) ON DELETE CASCADE,
      device_id     TEXT REFERENCES devices(id) ON DELETE SET NULL,
      zone_id       BIGINT REFERENCES attend_zones(id) ON DELETE SET NULL,
      person_id     BIGINT REFERENCES attend_people(id) ON DELETE SET NULL,
      credential_id BIGINT REFERENCES attend_credentials(id) ON DELETE SET NULL,
      card_number   BIGINT,
      direction     TEXT NOT NULL DEFAULT 'in',
      granted       BOOLEAN NOT NULL DEFAULT false,
      -- ok | unknown-card | offline | duplicate | not-allowed | out-of-hours |
      -- expired | revoked
      reason        TEXT NOT NULL DEFAULT 'ok',
      -- card | wiegand | rex | remote | manual | api
      method        TEXT NOT NULL DEFAULT 'card',
      source        TEXT NOT NULL DEFAULT 'device',
      device_seq    BIGINT,
      /*
       * What the terminal believed the time was, and null when it had no
       * clock at all. Kept beside the server's own timestamp rather than
       * replacing it: after an outage the two differ by the length of the
       * outage, and a register that quietly used arrival-at-the-server time
       * would show a whole morning of people arriving at once when the line
       * came back.
       */
      device_at     TIMESTAMPTZ,
      at            TIMESTAMPTZ NOT NULL DEFAULT now(),
      offline       BOOLEAN NOT NULL DEFAULT false,
      dedupe_key    TEXT UNIQUE,
      created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_attend_punches_site_at ON attend_punches(site_id, at DESC);
    CREATE INDEX IF NOT EXISTS idx_attend_punches_person ON attend_punches(person_id, at DESC);
    CREATE INDEX IF NOT EXISTS idx_attend_punches_device ON attend_punches(device_id, at DESC);
    CREATE INDEX IF NOT EXISTS idx_attend_punches_card ON attend_punches(site_id, card_number, at DESC);

    /*
     * One row per person per day: the register.
     *
     * Derived from punches and recomputable from them, and stored anyway.
     * Recomputing on read would mean a monthly report for eight hundred people
     * scanning four million punch rows, and — more importantly — a register
     * that silently changes after somebody has printed and signed it. This is
     * the record; the punches are the evidence for it.
     *
     * source says whether a human overrode it. A head of year marking somebody
     * present because the reader was broken must not be quietly reverted by
     * the next recompute, so a manual row is never overwritten by the
     * automatic one.
     */
    CREATE TABLE IF NOT EXISTS attend_days (
      id            BIGSERIAL PRIMARY KEY,
      site_id       BIGINT NOT NULL REFERENCES attend_sites(id) ON DELETE CASCADE,
      person_id     BIGINT NOT NULL REFERENCES attend_people(id) ON DELETE CASCADE,
      day           DATE NOT NULL,
      -- present | late | absent | half | leave | holiday | weekend | unknown
      status        TEXT NOT NULL DEFAULT 'unknown',
      first_in      TIMESTAMPTZ,
      last_out      TIMESTAMPTZ,
      worked_minutes INT NOT NULL DEFAULT 0,
      late_minutes  INT NOT NULL DEFAULT 0,
      early_minutes INT NOT NULL DEFAULT 0,
      punches       INT NOT NULL DEFAULT 0,
      -- Set when the day was closed by the auto-out rule rather than a scan,
      -- so a timesheet can show which hours were assumed.
      assumed_out   BOOLEAN NOT NULL DEFAULT false,
      note          TEXT NOT NULL DEFAULT '',
      -- auto | manual
      source        TEXT NOT NULL DEFAULT 'auto',
      /*
       * When a guardian or manager was told about this day.
       *
       * Kept on the row the notification is about, so "have we already said
       * this" is answered by the same unique key as everything else here
       * (person, day). A separate outbox table would be a second thing to keep
       * in step, and the failure it invites — telling a parent twice that
       * their child did not arrive — is one people remember.
       */
      notified_at   TIMESTAMPTZ,
      updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE UNIQUE INDEX IF NOT EXISTS idx_attend_days_person_day ON attend_days(person_id, day);
    CREATE INDEX IF NOT EXISTS idx_attend_days_site_day ON attend_days(site_id, day);
    -- Added after the table shipped, so existing deployments get the column.
    ALTER TABLE attend_days ADD COLUMN IF NOT EXISTS notified_at TIMESTAMPTZ;

    /*
     * Authorised absence, and site closures.
     *
     * One table for both because they are the same statement — "nobody is
     * expected here then" — differing only in who it covers. A row with no
     * person and no group is a site holiday; with a group, a class trip; with
     * a person, their leave.
     */
    CREATE TABLE IF NOT EXISTS attend_leaves (
      id            BIGSERIAL PRIMARY KEY,
      site_id       BIGINT NOT NULL REFERENCES attend_sites(id) ON DELETE CASCADE,
      person_id     BIGINT REFERENCES attend_people(id) ON DELETE CASCADE,
      group_id      BIGINT REFERENCES attend_groups(id) ON DELETE CASCADE,
      -- holiday | leave | sick | excused | trip | training | remote
      kind          TEXT NOT NULL DEFAULT 'leave',
      from_day      DATE NOT NULL,
      to_day        DATE NOT NULL,
      /*
       * Whether the person is expected to be at work despite not being here.
       * Working from home is an absence from the building and a normal working
       * day for a timesheet; a holiday is neither. Collapsing the two makes
       * one of the two reports wrong.
       */
      counts_as_present BOOLEAN NOT NULL DEFAULT false,
      note          TEXT NOT NULL DEFAULT '',
      approved_by   TEXT NOT NULL DEFAULT '',
      created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_attend_leaves_site ON attend_leaves(site_id, from_day, to_day);
    CREATE INDEX IF NOT EXISTS idx_attend_leaves_person ON attend_leaves(person_id, from_day);

    /*
     * Office access requests.
     *
     * "Can this person come into the building" asked as a request that is
     * recorded and decided, rather than inferred from having been given a card.
     * A card says somebody was issued a credential; it does not say anybody
     * agreed they should be in the office today, and after the fact those are
     * different questions — the second is the one asked in an incident review.
     *
     * Auto-approval is the normal path and is deliberately not the same thing
     * as no approval: an employee who is active and inside their validity dates
     * is approved on the spot, by the rule rather than by a person, and the row
     * records that it was 'auto'. A request that cannot be auto-approved stays
     * pending for somebody to decide, which is exactly the case worth a human.
     */
    CREATE TABLE IF NOT EXISTS attend_access_requests (
      id            BIGSERIAL PRIMARY KEY,
      site_id       BIGINT NOT NULL REFERENCES attend_sites(id) ON DELETE CASCADE,
      person_id     BIGINT NOT NULL REFERENCES attend_people(id) ON DELETE CASCADE,
      -- pending | approved | rejected | revoked
      status        TEXT NOT NULL DEFAULT 'pending',
      -- auto | the email of whoever decided it
      decided_by    TEXT NOT NULL DEFAULT '',
      reason        TEXT NOT NULL DEFAULT '',
      /*
       * Null means open-ended. A request for a specific day is how a visitor or
       * a contractor is handled without giving them a standing right to the
       * building.
       */
      valid_from    DATE,
      valid_to      DATE,
      requested_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
      decided_at    TIMESTAMPTZ
    );
    CREATE INDEX IF NOT EXISTS idx_attend_access_person ON attend_access_requests(person_id, status);
    CREATE INDEX IF NOT EXISTS idx_attend_access_site ON attend_access_requests(site_id, status, requested_at DESC);

    /*
     * What is being asked for.
     *
     * 'office-access' is the original meaning and stays the default, so every
     * existing row keeps saying what it already said. 'card-replacement' is a
     * different question entirely -- it asks for a lost badge to be reissued,
     * and approving it revokes the old one.
     *
     * They share a table because they share their whole machinery: raise,
     * approve, reject, record who decided. They must not share a query, which
     * is why every existing read filters on this column -- a replacement
     * request answering "may this person come in?" would let somebody through
     * a door on the strength of having lost their card.
     */
    ALTER TABLE attend_access_requests ADD COLUMN IF NOT EXISTS kind TEXT NOT NULL DEFAULT 'office-access';

    /*
     * Binding a card to a person by presenting it at a reader.
     *
     * A row is an open invitation for the next card to become somebody's
     * credential, which is why it carries an expiry rather than a flag. Left
     * open, the next person through the door loses their card to the record
     * being enrolled, and nothing about that looks like a failure to either of
     * them.
     */
    CREATE TABLE IF NOT EXISTS attend_enrolments (
      id           BIGSERIAL PRIMARY KEY,
      site_id      BIGINT NOT NULL REFERENCES attend_sites(id) ON DELETE CASCADE,
      person_id    BIGINT NOT NULL REFERENCES attend_people(id) ON DELETE CASCADE,
      device_id    TEXT NOT NULL,
      -- waiting | done | expired | cancelled | failed
      state        TEXT NOT NULL DEFAULT 'waiting',
      card_number  BIGINT,
      message      TEXT NOT NULL DEFAULT '',
      started_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
      expires_at   TIMESTAMPTZ NOT NULL,
      decided_at   TIMESTAMPTZ
    );
    CREATE INDEX IF NOT EXISTS idx_attend_enrol_device ON attend_enrolments(device_id, state, expires_at DESC);

    /*
     * Whether this site requires an approved request before a card opens a door.
     *
     * Default false, and that default is load-bearing. Turning this on for
     * every existing site would mean every card in every building stops working
     * the moment this deploys, which is the failure mode the empty-rule-table
     * comment in decide.ts already warns about. A site opts in when somebody
     * has decided to run it that way and has approved their people.
     */
    ALTER TABLE attend_sites ADD COLUMN IF NOT EXISTS require_access_request BOOLEAN NOT NULL DEFAULT false;


    /*
     * =========================== GUARDIAN ================================
     *
     * A personal safety beacon and the people it calls.
     *
     * The wearer is the one person who cannot be relied on to be reachable, so
     * everything here is arranged for whoever is trying to help them: contacts
     * are ordered, an incident is a first-class row rather than a device state
     * bit, and every position ever reported during one is kept.
     */

    /*
     * Who gets told, and in what order.
     *
     * The order is not decoration. The device calls the first contact by
     * voice after messaging everybody, because a ringing phone is noticed at
     * 3am and a text is not — so first place is a decision about who is most
     * likely to actually pick up, and the person setting this up needs to be
     * able to make it deliberately.
     *
     * The same list lives on the device in NVS, because the whole point is
     * that it works with no network, no phone and no platform. This table is
     * the copy the app edits and the device is provisioned from; the device's
     * copy is the one that matters in an emergency.
     */
    CREATE TABLE IF NOT EXISTS guardian_contacts (
      id            BIGSERIAL PRIMARY KEY,
      device_id     TEXT NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
      owner_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      name          TEXT NOT NULL,
      -- E.164, because it is going to a GSM modem that will not guess a
      -- country code the way a phone's dialler does.
      phone         TEXT NOT NULL,
      relation      TEXT NOT NULL DEFAULT '',
      position      INT NOT NULL DEFAULT 0,
      -- Whether this contact also receives push/email from the platform. A
      -- grandparent may want the SMS and not an app account.
      notify_push   BOOLEAN NOT NULL DEFAULT true,
      created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_guardian_contacts_device
      ON guardian_contacts(device_id, position);

    /*
     * A police station, with a location.
     *
     * "Nearest police station" cannot be computed on a device with no map and
     * no data connection, so the platform resolves it from this table and
     * pushes the number down to the device, which caches it. That is what
     * makes an SMS-only alarm reach the right station rather than a national
     * switchboard.
     *
     * Seeded per deployment. A station with no phone number is still useful —
     * it tells a responder where to go — so the phone is allowed to be empty
     * and the resolver skips those when choosing who to text.
     */
    CREATE TABLE IF NOT EXISTS guardian_police_stations (
      id            BIGSERIAL PRIMARY KEY,
      name          TEXT NOT NULL,
      phone         TEXT NOT NULL DEFAULT '',
      -- ISO-3166-1 alpha-2, so one table can serve more than one country and
      -- a resolver never returns a station across an ocean.
      country       TEXT NOT NULL DEFAULT '',
      district      TEXT NOT NULL DEFAULT '',
      lat           DOUBLE PRECISION NOT NULL,
      lng           DOUBLE PRECISION NOT NULL,
      active        BOOLEAN NOT NULL DEFAULT true,
      created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_guardian_police_country
      ON guardian_police_stations(country, active);

    /*
     * One emergency.
     *
     * An incident is a row and not a flag on the device, because the questions
     * asked afterwards are all about a period of time: when did it start, who
     * was told, did anyone answer, where did they go. A boolean on the device
     * answers none of them and is gone the moment it is cleared.
     *
     * The source column distinguishes the button from the app and from a test,
     * and the
     * distinction matters: a test must never look like an emergency in a
     * report, and an app-triggered panic did not involve the shoe at all.
     */
    CREATE TABLE IF NOT EXISTS guardian_incidents (
      id            BIGSERIAL PRIMARY KEY,
      device_id     TEXT NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
      owner_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      -- button | app | test
      source        TEXT NOT NULL DEFAULT 'button',
      -- open | acknowledged | resolved | false_alarm
      status        TEXT NOT NULL DEFAULT 'open',
      opened_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
      acknowledged_at TIMESTAMPTZ,
      acknowledged_by TEXT NOT NULL DEFAULT '',
      closed_at     TIMESTAMPTZ,
      /*
       * Where it started, and whether that was known.
       *
       * Nullable rather than zeroed: 0,0 is a real place in the Gulf of
       * Guinea, and a map pin drawn from it is indistinguishable from a
       * genuine one. The firmware refuses to send it for the same reason.
       */
      opened_lat    DOUBLE PRECISION,
      opened_lng    DOUBLE PRECISION,
      -- The station this was routed to, resolved at the moment it opened.
      station_id    BIGINT REFERENCES guardian_police_stations(id) ON DELETE SET NULL,
      station_km    DOUBLE PRECISION,
      note          TEXT NOT NULL DEFAULT ''
    );
    CREATE INDEX IF NOT EXISTS idx_guardian_incidents_device
      ON guardian_incidents(device_id, opened_at DESC);
    /*
     * At most one open incident per device.
     *
     * Without this, a device that republishes sos=true — a reconnect, a
     * retained message, a heartbeat during the emergency — opens a second
     * incident, and the contacts get told twice about one event. Partial, so
     * the history is unconstrained.
     */
    CREATE UNIQUE INDEX IF NOT EXISTS uq_guardian_incident_open
      ON guardian_incidents(device_id) WHERE status IN ('open', 'acknowledged');

    /*
     * Every position reported while an incident was running.
     *
     * Kept in full. A track is what lets somebody following on foot know which
     * way the wearer went, and it is the part that cannot be reconstructed
     * afterwards from anything else.
     */
    CREATE TABLE IF NOT EXISTS guardian_incident_points (
      id            BIGSERIAL PRIMARY KEY,
      incident_id   BIGINT NOT NULL REFERENCES guardian_incidents(id) ON DELETE CASCADE,
      at            TIMESTAMPTZ NOT NULL DEFAULT now(),
      lat           DOUBLE PRECISION NOT NULL,
      lng           DOUBLE PRECISION NOT NULL,
      -- Age of the GPS fix when it was reported. A point from a two-hour-old
      -- fix is a different kind of fact from a live one and must not be drawn
      -- on a map as though it were current.
      fix_age_sec   INT NOT NULL DEFAULT 0,
      battery       INT
    );
    CREATE INDEX IF NOT EXISTS idx_guardian_points_incident
      ON guardian_incident_points(incident_id, at);

    /*
     * Who was told, how, and whether it worked.
     *
     * The single most important question after an incident is "did anybody
     * actually get it", and the honest answer is usually different per channel
     * — the SMS delivered, the push failed because the phone was off. Storing
     * one "notified" boolean loses exactly the detail that matters.
     */
    CREATE TABLE IF NOT EXISTS guardian_notifications (
      id            BIGSERIAL PRIMARY KEY,
      incident_id   BIGINT NOT NULL REFERENCES guardian_incidents(id) ON DELETE CASCADE,
      -- contact | police | owner
      target        TEXT NOT NULL,
      target_name   TEXT NOT NULL DEFAULT '',
      -- sms | call | push | email
      channel       TEXT NOT NULL,
      -- device | platform. The device sends its own SMS over GSM; the platform
      -- sends push and email. Both are recorded here so one timeline shows
      -- everything that was attempted.
      sent_by       TEXT NOT NULL DEFAULT 'platform',
      ok            BOOLEAN NOT NULL DEFAULT false,
      detail        TEXT NOT NULL DEFAULT '',
      at            TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_guardian_notifications_incident
      ON guardian_notifications(incident_id, at);

    /*
     * Safe zones — "tell me when they leave school".
     *
     * Not tracking. The position is already reported for the sake of an
     * emergency; a zone turns it into one sentence a parent can act on instead
     * of a map somebody has to watch.
     *
     * The radius is metres and the hysteresis that stops a wearer standing at
     * the gate from generating an alert every ninety seconds lives in
     * guardian/geofence.ts, not here — it is a property of GPS noise, not of
     * any particular school.
     */
    CREATE TABLE IF NOT EXISTS guardian_zones (
      id            BIGSERIAL PRIMARY KEY,
      device_id     TEXT NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
      owner_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      name          TEXT NOT NULL,
      lat           DOUBLE PRECISION NOT NULL,
      lng           DOUBLE PRECISION NOT NULL,
      radius_m      INT NOT NULL DEFAULT 200,
      notify_enter  BOOLEAN NOT NULL DEFAULT true,
      notify_exit   BOOLEAN NOT NULL DEFAULT true,
      /*
       * Where the wearer was last known to be, relative to this zone.
       *
       * Persisted rather than held in memory because it is the only thing
       * stopping a restart from re-announcing every departure that had already
       * been reported. NULL means "never seen", which is deliberately not the
       * same as "outside" — the first sighting is recorded silently, since the
       * wearer did not just arrive anywhere, we only just started looking.
       */
      presence      TEXT,
      created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_guardian_zones_device ON guardian_zones(device_id);

    /*
     * Journey mode — "walk me home".
     *
     * Covers what the panic button cannot: being unable to press it. The
     * deadline is also armed on the device itself, so a wearer who walks out of
     * coverage is still covered; this row is what the app shows and what
     * re-arms the device when it comes back.
     */
    CREATE TABLE IF NOT EXISTS guardian_journeys (
      id            BIGSERIAL PRIMARY KEY,
      device_id     TEXT NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
      owner_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      destination   TEXT NOT NULL DEFAULT '',
      started_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
      due_at        TIMESTAMPTZ NOT NULL,
      -- running | arrived | overdue | cancelled
      status        TEXT NOT NULL DEFAULT 'running',
      nudged_at     TIMESTAMPTZ,
      closed_at     TIMESTAMPTZ
    );
    CREATE INDEX IF NOT EXISTS idx_guardian_journeys_device
      ON guardian_journeys(device_id, started_at DESC);
    /* One journey at a time, for the same reason as one open incident. */
    CREATE UNIQUE INDEX IF NOT EXISTS uq_guardian_journey_running
      ON guardian_journeys(device_id) WHERE status = 'running';

    /*
     * How far an unacknowledged incident has been pushed.
     *
     * Stored on the incident because the sweep runs on a timer: without a
     * record of what has already been done, an alarm that is ten minutes old
     * re-notifies everybody on every pass — a fresh wave of messages every
     * minute to people who are already on their way.
     */
    ALTER TABLE guardian_incidents
      ADD COLUMN IF NOT EXISTS escalated TEXT NOT NULL DEFAULT '';


    /*
     * ============================ DRONE ==================================
     *
     * A flight, from arm to disarm.
     *
     * The flight — not the device, and not the day — is the unit everything
     * else hangs off, because it is the unit a person thinks in: "the survey
     * this morning", "the one where the battery got low". Storing only a
     * stream of positions and reconstructing flights from gaps in it was the
     * obvious alternative and was rejected: a radio dropout in the middle of a
     * long transect is indistinguishable from a landing followed by a
     * take-off, so the log book would invent flights that never happened and
     * merge ones that did.
     *
     * Arm and disarm are unambiguous, they come from the autopilot rather than
     * from our inference, and they are exactly the boundary a regulator asks
     * about.
     */
    CREATE TABLE IF NOT EXISTS flights (
      id             BIGSERIAL PRIMARY KEY,
      owner_id       BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      device_id      TEXT NOT NULL,
      -- Identifies a power cycle of the companion computer. Two flights with
      -- different boot ids cannot be the same flight, however close in time.
      boot_id        BIGINT NOT NULL DEFAULT 0,
      started_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
      ended_at       TIMESTAMPTZ,
      /*
       * "took_off_at" is not "started_at". Arming and leaving the ground are
       * different moments, sometimes minutes apart while the pilot waits for
       * a clearance, and billing or duty-time built on the wrong one is wrong
       * by exactly that much. NULL means the aircraft armed and never flew,
       * which is a real and common outcome worth being able to count.
       */
      took_off_at    TIMESTAMPTZ,
      landed_at      TIMESTAMPTZ,
      max_alt_m      REAL NOT NULL DEFAULT 0,
      max_dist_m     REAL NOT NULL DEFAULT 0,
      distance_m     REAL NOT NULL DEFAULT 0,
      max_speed_ms   REAL NOT NULL DEFAULT 0,
      batt_start_pct INT,
      batt_end_pct   INT,
      batt_used_mah  REAL,
      home_lat       DOUBLE PRECISION,
      home_lon       DOUBLE PRECISION,
      samples        INT NOT NULL DEFAULT 0,
      /*
       * How the flight ended. "open" while it is in progress; "landed" on a
       * clean disarm; "stale" when the aircraft stopped reporting and never
       * came back — deliberately NOT folded into "landed", because a flight
       * that ends in silence is the one an investigator most wants to find,
       * and a log that quietly calls it a landing hides it.
       */
      outcome        TEXT NOT NULL DEFAULT 'open',
      failsafe       BOOLEAN NOT NULL DEFAULT false,
      fence_breach   BOOLEAN NOT NULL DEFAULT false,
      notes          TEXT,
      created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_flights_owner ON flights(owner_id, started_at DESC);
    CREATE INDEX IF NOT EXISTS idx_flights_device ON flights(device_id, started_at DESC);
    -- "Is this aircraft flying right now" must not scan the log book.
    CREATE INDEX IF NOT EXISTS idx_flights_open ON flights(device_id) WHERE outcome = 'open';

    /*
     * Position samples.
     *
     * Columns rather than a JSONB blob: a track is queried by range far more
     * often than by key ("everything above 100 m", "where was it at 14:32"),
     * and every sample carries exactly the same fields, so JSONB would buy
     * nothing and cost roughly three times the storage per row.
     */
    CREATE TABLE IF NOT EXISTS flight_track (
      id           BIGSERIAL PRIMARY KEY,
      flight_id    BIGINT NOT NULL REFERENCES flights(id) ON DELETE CASCADE,
      at           TIMESTAMPTZ NOT NULL,
      lat          DOUBLE PRECISION NOT NULL,
      lon          DOUBLE PRECISION NOT NULL,
      alt_m        REAL NOT NULL,
      alt_msl_m    REAL,
      heading_deg  REAL,
      speed_ms     REAL,
      climb_ms     REAL,
      batt_v       REAL,
      batt_pct     INT,
      sats         INT,
      hdop         REAL,
      mode         TEXT,
      roll_deg     REAL,
      pitch_deg    REAL,
      dist_home_m  REAL,
      flags        INT NOT NULL DEFAULT 0
    );
    CREATE INDEX IF NOT EXISTS idx_flight_track_flight ON flight_track(flight_id, at);

    /*
     * Discrete events within a flight: armed, took off, mode changed, failsafe,
     * fence breach, landed, and every command we sent plus whether it was
     * refused.
     *
     * Kept apart from the customer-facing "events" feed for the same reason
     * device_audit is: that feed answers "what did my house do" and the
     * customer can clear it. This is the flight record, and it has to survive
     * the customer tidying up — it is what gets read after an accident.
     */
    CREATE TABLE IF NOT EXISTS flight_events (
      id         BIGSERIAL PRIMARY KEY,
      flight_id  BIGINT REFERENCES flights(id) ON DELETE CASCADE,
      device_id  TEXT NOT NULL,
      owner_id   BIGINT REFERENCES users(id) ON DELETE CASCADE,
      at         TIMESTAMPTZ NOT NULL DEFAULT now(),
      kind       TEXT NOT NULL,
      detail     JSONB NOT NULL DEFAULT '{}'::jsonb,
      severity   TEXT NOT NULL DEFAULT 'info'
    );
    CREATE INDEX IF NOT EXISTS idx_flight_events_flight ON flight_events(flight_id, at);
    CREATE INDEX IF NOT EXISTS idx_flight_events_owner ON flight_events(owner_id, at DESC);

    /*
     * Saved waypoint missions.
     *
     * Stored here and uploaded to the autopilot on request rather than being
     * flown from here: the autopilot must hold the mission, because it has to
     * keep flying it when this link goes away. A mission that only existed in
     * the cloud would stop at the first dropout.
     */
    CREATE TABLE IF NOT EXISTS drone_missions (
      id         BIGSERIAL PRIMARY KEY,
      owner_id   BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      name       TEXT NOT NULL,
      waypoints  JSONB NOT NULL DEFAULT '[]'::jsonb,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_drone_missions_owner ON drone_missions(owner_id, name);

    /*
     * Per-account drone policy and the battery register.
     *
     * Limits here are advisory: they are what the console shows and what the
     * daily report is measured against. The enforcing copy lives on the
     * aircraft, because a limit that needs a network round-trip to apply is
     * not a limit.
     */
    CREATE TABLE IF NOT EXISTS drone_settings (
      owner_id        BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
      max_alt_m       INT NOT NULL DEFAULT 120,
      max_range_m     INT NOT NULL DEFAULT 500,
      min_batt_pct    INT NOT NULL DEFAULT 25,
      -- Operator identification, required in most jurisdictions for anything
      -- above toy weight. Free text because the format differs per country.
      operator_id     TEXT,
      report_email    TEXT,
      report_hour     INT NOT NULL DEFAULT 7,
      alert_failsafe  BOOLEAN NOT NULL DEFAULT true,
      alert_fence     BOOLEAN NOT NULL DEFAULT true,
      alert_low_batt  BOOLEAN NOT NULL DEFAULT true,
      updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    /*
     * Flight batteries, tracked as assets.
     *
     * A lithium pack is the only part of a multirotor that wears out on a
     * schedule a person can act on, and cycle count is how it is measured
     * everywhere in the industry. Counting cycles per pack — rather than
     * flight hours per airframe — is what lets the console say "this pack has
     * done 180 cycles, retire it" instead of "something on this aircraft is
     * old".
     */
    CREATE TABLE IF NOT EXISTS drone_batteries (
      id           BIGSERIAL PRIMARY KEY,
      owner_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      label        TEXT NOT NULL,
      cells        INT NOT NULL DEFAULT 4,
      capacity_mah INT NOT NULL DEFAULT 5000,
      cycles       INT NOT NULL DEFAULT 0,
      retire_at    INT NOT NULL DEFAULT 200,
      first_used   TIMESTAMPTZ,
      last_used    TIMESTAMPTZ,
      retired      BOOLEAN NOT NULL DEFAULT false,
      notes        TEXT,
      created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_drone_batteries_owner ON drone_batteries(owner_id, retired);
    ALTER TABLE flights ADD COLUMN IF NOT EXISTS battery_id BIGINT;
  `);

  await backfillSerials();
}

/**
 * Gives existing devices a serial.
 *
 * Runs once in practice — the UPDATE matches nothing on every later boot — but
 * has to exist, because without it the registry's whole premise ("read the
 * number off the unit and find it") would work for devices sold after this
 * shipped and fail for every device already in the field.
 *
 * Serials are derived from the hardware id embedded in the device id, so they
 * are stable: running this twice cannot produce a different answer, and a
 * device that is later re-provisioned keeps the number on its label.
 */
async function backfillSerials(): Promise<void> {
  const { rows } = await pool.query<{ id: string; type: string }>(
    `SELECT id, type FROM devices WHERE serial IS NULL`
  );
  if (!rows.length) return;

  let filled = 0;
  for (const d of rows) {
    // The chip id is the tail of `${type}-${hwid}`; fall back to the whole id
    // for anything that does not follow that shape.
    const hwid = d.id.startsWith(`${d.type}-`) ? d.id.slice(d.type.length + 1) : d.id;
    let serial = generateSerial(d.type, hwid);
    // A collision is possible in principle (7 payload characters, derived).
    // Retry with a random payload rather than leave the row without a serial.
    for (let attempt = 0; attempt < 5; attempt++) {
      const clash = await pool.query(`SELECT 1 FROM devices WHERE serial = $1 AND id <> $2`, [serial, d.id]);
      if (!clash.rowCount) break;
      serial = generateSerial(d.type);
    }
    try {
      await pool.query(`UPDATE devices SET serial = $2, hwid = COALESCE(NULLIF(hwid,''), $3) WHERE id = $1`, [
        d.id,
        serial,
        hwid,
      ]);
      filled++;
    } catch {
      /* a concurrent boot won the race for this serial — it has one either way */
    }
  }
  if (filled) logger.info({ filled }, "backfilled device serials");
}

/** Records an administrative action against a device (best-effort). */
export async function recordDeviceAudit(
  deviceId: string,
  actor: { uid: number; email: string } | null,
  action: string,
  detail: Record<string, unknown> = {},
  note = ""
): Promise<void> {
  try {
    await pool.query(
      `INSERT INTO device_audit (device_id, actor_id, actor_email, action, detail, note)
       VALUES ($1, $2, $3, $4, $5, $6)`,
      [deviceId, actor?.uid ?? null, actor?.email ?? "", action, detail, note]
    );
  } catch (err) {
    logger.error({ err, deviceId, action }, "device audit insert failed");
  }
}

/** Record an event for the notification center / activity log (best-effort). */
export async function recordEvent(
  ownerId: number,
  kind: string,
  title: string,
  body = "",
  deviceId: string | null = null
): Promise<void> {
  try {
    await pool.query(
      `INSERT INTO events (owner_id, device_id, kind, title, body) VALUES ($1, $2, $3, $4, $5)`,
      [ownerId, deviceId, kind, title, body]
    );
  } catch {
    /* best-effort: never block the caller on the activity feed */
  }
}
