// The native Android client.
//
// Deliberately a separate Gradle build from mobile/android: that project is
// generated by `expo prebuild` and is overwritten wholesale every time it runs.
// Anything of ours living inside it would be deleted by a routine command, so
// this build stands on its own and shares nothing with it but the SDK.

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "CircuventNative"
include(":app")
